// CAT-019 — Clasificación de Actividades Económicas del Ministerio de Hacienda de El Salvador
// Basado en CIIU Rev. 4 adaptado para el sistema de facturación electrónica (DTE).
// Fuente de verdad: https://docs.facturallama.com/appendixes/cat-019 (771 códigos).
// Códigos y descripciones se regeneran desde esa tabla — no editarlos a mano. El
// backend valida contra la misma lista (server/src/lib/cat019.ts): un código que
// exista aquí y no allá se traduce en un 400 sobre una opción que el usuario sí ve.
// El sector NO viene de la tabla: se deriva de la división CIIU (2 primeros dígitos).

export type ActividadEconomica = {
  codigo: string;
  descripcion: string;
  sector: string;
};

// Los sectores deben coincidir exactamente con los valores de SECTORES_CAT019 más abajo.
export const SECTORES_CAT019 = [
  'Agricultura, ganadería y pesca',
  'Minería y canteras',
  'Manufactura',
  'Electricidad y gas',
  'Agua y saneamiento',
  'Construcción',
  'Comercio',
  'Transporte y almacenamiento',
  'Alojamiento y restaurantes',
  'Información y comunicaciones',
  'Servicios financieros',
  'Bienes raíces',
  'Servicios profesionales y técnicos',
  'Servicios administrativos',
  'Administración pública',
  'Educación',
  'Salud',
  'Cultura y entretenimiento',
  'Otros servicios',
  'Hogares como empleadores',
  'Organizaciones extraterritoriales',
  'Empleados y personas naturales',
] as const;

export type SectorCAT019 = typeof SECTORES_CAT019[number];

const A = 'Agricultura, ganadería y pesca';
const B = 'Minería y canteras';
const C = 'Manufactura';
const D = 'Electricidad y gas';
const E = 'Agua y saneamiento';
const F = 'Construcción';
const G = 'Comercio';
const H = 'Transporte y almacenamiento';
const I = 'Alojamiento y restaurantes';
const J = 'Información y comunicaciones';
const K = 'Servicios financieros';
const L = 'Bienes raíces';
const M = 'Servicios profesionales y técnicos';
const N = 'Servicios administrativos';
const O = 'Administración pública';
const P = 'Educación';
const Q = 'Salud';
const R = 'Cultura y entretenimiento';
const S = 'Otros servicios';
const T = 'Hogares como empleadores';
const U = 'Organizaciones extraterritoriales';
const Z = 'Empleados y personas naturales';

export const ACTIVIDADES_ECONOMICAS_SV: ActividadEconomica[] = [
  // ── A · Agricultura, ganadería, silvicultura y pesca ──────────────────────
  { codigo: '01111', descripcion: 'Cultivo de cereales excepto arroz y para forrajes', sector: A },
  { codigo: '01112', descripcion: 'Cultivo de legumbres', sector: A },
  { codigo: '01113', descripcion: 'Cultivo de semillas oleaginosas', sector: A },
  { codigo: '01114', descripcion: 'Cultivo de plantas para la preparación de semillas', sector: A },
  { codigo: '01119', descripcion: 'Cultivo de otros cereales excepto arroz y forrajeros n.c.p.', sector: A },
  { codigo: '01120', descripcion: 'Cultivo de arroz', sector: A },
  { codigo: '01131', descripcion: 'Cultivo de raíces y tubérculos', sector: A },
  { codigo: '01132', descripcion: 'Cultivo de brotes, bulbos, vegetales tubérculos y cultivos similares', sector: A },
  { codigo: '01133', descripcion: 'Cultivo hortícola de fruto', sector: A },
  { codigo: '01134', descripcion: 'Cultivo de hortalizas de hoja y otras hortalizas ncp', sector: A },
  { codigo: '01140', descripcion: 'Cultivo de caña de azúcar', sector: A },
  { codigo: '01150', descripcion: 'Cultivo de tabaco', sector: A },
  { codigo: '01161', descripcion: 'Cultivo de algodón', sector: A },
  { codigo: '01162', descripcion: 'Cultivo de fibras vegetales excepto algodón', sector: A },
  { codigo: '01191', descripcion: 'Cultivo de plantas no perennes para la producción de semillas y flores', sector: A },
  { codigo: '01192', descripcion: 'Cultivo de cereales y pastos para la alimentación animal', sector: A },
  { codigo: '01199', descripcion: 'Producción de cultivos no estacionales ncp', sector: A },
  { codigo: '01220', descripcion: 'Cultivo de frutas tropicales', sector: A },
  { codigo: '01230', descripcion: 'Cultivo de cítricos', sector: A },
  { codigo: '01240', descripcion: 'Cultivo de frutas de pepita y hueso', sector: A },
  { codigo: '01251', descripcion: 'Cultivo de frutas ncp', sector: A },
  { codigo: '01252', descripcion: 'Cultivo de otros frutos y nueces de árboles y arbustos', sector: A },
  { codigo: '01260', descripcion: 'Cultivo de frutos oleaginosos', sector: A },
  { codigo: '01271', descripcion: 'Cultivo de café', sector: A },
  { codigo: '01272', descripcion: 'Cultivo de plantas para la elaboración de bebidas excepto café', sector: A },
  { codigo: '01281', descripcion: 'Cultivo de especias y aromáticas', sector: A },
  { codigo: '01282', descripcion: 'Cultivo de plantas para la obtención de productos medicinales y farmacéuticos', sector: A },
  { codigo: '01291', descripcion: 'Cultivo de árboles de hule (caucho) para la obtención de látex', sector: A },
  { codigo: '01292', descripcion: 'Cultivo de plantas para la obtención de productos químicos y colorantes', sector: A },
  { codigo: '01299', descripcion: 'Producción de cultivos perennes ncp', sector: A },
  { codigo: '01300', descripcion: 'Propagación de plantas', sector: A },
  { codigo: '01301', descripcion: 'Cultivo de plantas y flores ornamentales', sector: A },
  { codigo: '01410', descripcion: 'Cría y engorde de ganado bovino', sector: A },
  { codigo: '01420', descripcion: 'Cría de caballos y otros equinos', sector: A },
  { codigo: '01440', descripcion: 'Cría de ovejas y cabras', sector: A },
  { codigo: '01450', descripcion: 'Cría de cerdos', sector: A },
  { codigo: '01460', descripcion: 'Cría de aves de corral y producción de huevos', sector: A },
  { codigo: '01491', descripcion: 'Cría de abejas apicultura para la obtención de miel y otros productos apícolas', sector: A },
  { codigo: '01492', descripcion: 'Cría de conejos', sector: A },
  { codigo: '01493', descripcion: 'Cría de iguanas y garrobos', sector: A },
  { codigo: '01494', descripcion: 'Cría de mariposas y otros insectos', sector: A },
  { codigo: '01499', descripcion: 'Cría y obtención de productos animales n.c.p.', sector: A },
  { codigo: '01500', descripcion: 'Cultivo de productos agrícolas en combinación con la cría de animales', sector: A },
  { codigo: '01611', descripcion: 'Servicios de maquinaria agrícola', sector: A },
  { codigo: '01612', descripcion: 'Control de plagas', sector: A },
  { codigo: '01613', descripcion: 'Servicios de riego', sector: A },
  { codigo: '01614', descripcion: 'Servicios de contratación de mano de obra para la agricultura', sector: A },
  { codigo: '01619', descripcion: 'Servicios agrícolas ncp', sector: A },
  { codigo: '01621', descripcion: 'Actividades para mejorar la reproducción, el crecimiento y el rendimiento de los animales y sus productos', sector: A },
  { codigo: '01622', descripcion: 'Servicios de mano de obra pecuaria', sector: A },
  { codigo: '01629', descripcion: 'Servicios pecuarios ncp', sector: A },
  { codigo: '01631', descripcion: 'Labores post cosecha de preparación de los productos agrícolas para su comercialización o para la industria', sector: A },
  { codigo: '01632', descripcion: 'Servicio de beneficio de café', sector: A },
  { codigo: '01633', descripcion: 'Servicio de beneficiado de plantas textiles (incluye el beneficiado cuando este es realizado en la misma explotación agropecuaria)', sector: A },
  { codigo: '01640', descripcion: 'Tratamiento de semillas para la propagación', sector: A },
  { codigo: '01700', descripcion: 'Caza ordinaria y mediante trampas, repoblación de animales de caza y servicios conexos', sector: A },
  { codigo: '02100', descripcion: 'Silvicultura y otras actividades forestales', sector: A },
  { codigo: '02200', descripcion: 'Extracción de madera', sector: A },
  { codigo: '02300', descripcion: 'Recolección de productos diferentes a la madera', sector: A },
  { codigo: '02400', descripcion: 'Servicios de apoyo a la silvicultura', sector: A },
  { codigo: '03110', descripcion: 'Pesca marítima de altura y costera', sector: A },
  { codigo: '03120', descripcion: 'Pesca de agua dulce', sector: A },
  { codigo: '03210', descripcion: 'Acuicultura marítima', sector: A },
  { codigo: '03220', descripcion: 'Acuicultura de agua dulce', sector: A },
  { codigo: '03300', descripcion: 'Servicios de apoyo a la pesca y acuicultura', sector: A },

  // ── B · Explotación de minas y canteras ───────────────────────────────────
  { codigo: '05100', descripcion: 'Extracción de hulla', sector: B },
  { codigo: '05200', descripcion: 'Extracción y aglomeración de lignito', sector: B },
  { codigo: '06100', descripcion: 'Extracción de petróleo crudo', sector: B },
  { codigo: '06200', descripcion: 'Extracción de gas natural', sector: B },
  { codigo: '07100', descripcion: 'Extracción de minerales de hierro', sector: B },
  { codigo: '07210', descripcion: 'Extracción de minerales de uranio y torio', sector: B },
  { codigo: '07290', descripcion: 'Extracción de minerales metalíferos no ferrosos', sector: B },
  { codigo: '08100', descripcion: 'Extracción de piedra, arena y arcilla', sector: B },
  { codigo: '08910', descripcion: 'Extracción de minerales para la fabricación de abonos y productos químicos', sector: B },
  { codigo: '08920', descripcion: 'Extracción y aglomeración de turba', sector: B },
  { codigo: '08930', descripcion: 'Extracción de sal', sector: B },
  { codigo: '08990', descripcion: 'Explotación de otras minas y canteras ncp', sector: B },
  { codigo: '09100', descripcion: 'Actividades de apoyo a la extracción de petróleo y gas natural', sector: B },
  { codigo: '09900', descripcion: 'Actividades de apoyo a la explotación de minas y canteras', sector: B },

  // ── C · Industrias manufactureras ─────────────────────────────────────────
  { codigo: '10101', descripcion: 'Servicio de rastros y mataderos de bovinos y porcinos', sector: C },
  { codigo: '10102', descripcion: 'Matanza y procesamiento de bovinos y porcinos', sector: C },
  { codigo: '10103', descripcion: 'Matanza y procesamientos de aves de corral', sector: C },
  { codigo: '10104', descripcion: 'Elaboración y conservación de embutidos y tripas naturales', sector: C },
  { codigo: '10105', descripcion: 'Servicios de conservación y empaque de carnes', sector: C },
  { codigo: '10106', descripcion: 'Elaboración y conservación de grasas y aceites animales', sector: C },
  { codigo: '10107', descripcion: 'Servicios de molienda de carne', sector: C },
  { codigo: '10108', descripcion: 'Elaboración de productos de carne ncp', sector: C },
  { codigo: '10201', descripcion: 'Procesamiento y conservación de pescado, crustáceos y moluscos', sector: C },
  { codigo: '10209', descripcion: 'Fabricación de productos de pescado ncp', sector: C },
  { codigo: '10301', descripcion: 'Elaboración de jugos de frutas y hortalizasv', sector: C },
  { codigo: '10302', descripcion: 'Elaboración y envase de jaleas, mermeladas y frutas deshidratadas', sector: C },
  { codigo: '10309', descripcion: 'Elaboración de productos de frutas y hortalizas n.c.p.', sector: C },
  { codigo: '10401', descripcion: 'Fabricación de aceites y grasas vegetales y animales comestibles', sector: C },
  { codigo: '10402', descripcion: 'Fabricación de aceites y grasas vegetales y animales no comestibles', sector: C },
  { codigo: '10409', descripcion: 'Servicio de maquilado de aceites', sector: C },
  { codigo: '10501', descripcion: 'Fabricación de productos lácteos excepto sorbetes y quesos sustitutos', sector: C },
  { codigo: '10502', descripcion: 'Fabricación de sorbetes y helados', sector: C },
  { codigo: '10503', descripcion: 'Fabricación de quesos', sector: C },
  { codigo: '10611', descripcion: 'Molienda de cereales', sector: C },
  { codigo: '10612', descripcion: 'Elaboración de cereales para el desayuno y similares', sector: C },
  { codigo: '10613', descripcion: 'Servicios de beneficiado de productos agrícolas ncp (excluye Beneficio de azúcar rama 1072 y beneficio de café rama 0163)', sector: C },
  { codigo: '10621', descripcion: 'Fabricación de almidón', sector: C },
  { codigo: '10628', descripcion: 'Servicio de molienda de maíz húmedo molino para nixtamal', sector: C },
  { codigo: '10711', descripcion: 'Elaboración de tortillas', sector: C },
  { codigo: '10712', descripcion: 'Fabricación de pan, galletas y barquillos', sector: C },
  { codigo: '10713', descripcion: 'Fabricación de repostería', sector: C },
  { codigo: '10721', descripcion: 'Ingenios azucareros', sector: C },
  { codigo: '10722', descripcion: 'Molienda de caña de azúcar para la elaboración de dulces', sector: C },
  { codigo: '10723', descripcion: 'Elaboración de jarabes de azúcar y otros similares', sector: C },
  { codigo: '10724', descripcion: 'Maquilado de azúcar de caña', sector: C },
  { codigo: '10730', descripcion: 'Fabricación de cacao, chocolates y productos de confitería', sector: C },
  { codigo: '10740', descripcion: 'Elaboración de macarrones, fideos, y productos farináceos similares', sector: C },
  { codigo: '10750', descripcion: 'Elaboración de comidas y platos preparados para la reventa en', sector: C },
  { codigo: '10791', descripcion: 'Elaboración de productos de café', sector: C },
  { codigo: '10792', descripcion: 'Elaboración de especies, sazonadores y condimentos', sector: C },
  { codigo: '10793', descripcion: 'Elaboración de sopas, cremas y consomé', sector: C },
  { codigo: '10794', descripcion: 'Fabricación de bocadillos tostados y/o fritos', sector: C },
  { codigo: '10799', descripcion: 'Elaboración de productos alimenticios ncp', sector: C },
  { codigo: '10800', descripcion: 'Elaboración de alimentos preparados para animales', sector: C },
  { codigo: '11012', descripcion: 'Fabricación de aguardiente y licores', sector: C },
  { codigo: '11020', descripcion: 'Elaboración de vinos', sector: C },
  { codigo: '11030', descripcion: 'Fabricación de cerveza', sector: C },
  { codigo: '11041', descripcion: 'Fabricación de aguas gaseosas', sector: C },
  { codigo: '11042', descripcion: 'Fabricación y envasado de agua', sector: C },
  { codigo: '11043', descripcion: 'Elaboración de refrescos', sector: C },
  { codigo: '11048', descripcion: 'Maquilado de aguas gaseosas', sector: C },
  { codigo: '11049', descripcion: 'Elaboración de bebidas no alcohólicas', sector: C },
  { codigo: '12000', descripcion: 'Elaboración de productos de tabaco', sector: C },
  { codigo: '13111', descripcion: 'Preparación de fibras textiles', sector: C },
  { codigo: '13112', descripcion: 'Fabricación de hilados', sector: C },
  { codigo: '13120', descripcion: 'Fabricación de telas', sector: C },
  { codigo: '13130', descripcion: 'Acabado de productos textiles', sector: C },
  { codigo: '13910', descripcion: 'Fabricación de tejidos de punto y ganchillo', sector: C },
  { codigo: '13921', descripcion: 'Fabricación de productos textiles para el hogar', sector: C },
  { codigo: '13922', descripcion: 'Sacos, bolsas y otros artículos textiles', sector: C },
  { codigo: '13929', descripcion: 'Fabricación de artículos confeccionados con materiales textiles, excepto prendas de vestir ncp', sector: C },
  { codigo: '13930', descripcion: 'Fabricación de tapices y alfombras', sector: C },
  { codigo: '13941', descripcion: 'Fabricación de cuerdas de henequén y otras fibras naturales (lazos, pitas)', sector: C },
  { codigo: '13942', descripcion: 'Fabricación de redes de diversos materiales', sector: C },
  { codigo: '13948', descripcion: 'Maquilado de productos trenzables de cualquier material (petates, sillas, etc.)', sector: C },
  { codigo: '13991', descripcion: 'Fabricación de adornos, etiquetas y otros artículos para prendas de vestir', sector: C },
  { codigo: '13992', descripcion: 'Servicio de bordados en artículos y prendas de tela', sector: C },
  { codigo: '13999', descripcion: 'Fabricación de productos textiles ncp', sector: C },
  { codigo: '14101', descripcion: 'Fabricación de ropa interior, para dormir y similares', sector: C },
  { codigo: '14102', descripcion: 'Fabricación de ropa para niños', sector: C },
  { codigo: '14103', descripcion: 'Fabricación de prendas de vestir para ambos sexos', sector: C },
  { codigo: '14104', descripcion: 'Confección de prendas a medida', sector: C },
  { codigo: '14105', descripcion: 'Fabricación de prendas de vestir para deportes', sector: C },
  { codigo: '14106', descripcion: 'Elaboración de artesanías de uso personal confeccionadas', sector: C },
  { codigo: '14108', descripcion: 'Maquilado de prendas de vestir, accesorios y otros', sector: C },
  { codigo: '14109', descripcion: 'Fabricación de prendas y accesorios de vestir n.c.p.', sector: C },
  { codigo: '14200', descripcion: 'Fabricación de artículos de piel', sector: C },
  { codigo: '14301', descripcion: 'Fabricación de calcetines, calcetas, medias (panty house) y otros', sector: C },
  { codigo: '14302', descripcion: 'Fabricación de ropa interior de tejido de punto', sector: C },
  { codigo: '14309', descripcion: 'Fabricación de prendas de vestir de tejido de punto ncp', sector: C },
  { codigo: '15110', descripcion: 'Curtido y adobo de cueros; adobo y teñido de pieles', sector: C },
  { codigo: '15121', descripcion: 'Fabricación de maletas, bolsos de mano y otros artículos de marroquinería', sector: C },
  { codigo: '15122', descripcion: 'Fabricación de monturas, accesorios y vainas talabartería', sector: C },
  { codigo: '15123', descripcion: 'Fabricación de artesanías principalmente de cuero natural y sintético', sector: C },
  { codigo: '15128', descripcion: 'Maquilado de artículos de cuero natural, sintético y de otros materiales', sector: C },
  { codigo: '15201', descripcion: 'Fabricación de calzado', sector: C },
  { codigo: '15202', descripcion: 'Fabricación de partes y accesorios de calzado', sector: C },
  { codigo: '15208', descripcion: 'Maquilado de partes y accesorios de calzado', sector: C },
  { codigo: '16100', descripcion: 'Aserradero y acepil adura de madera', sector: C },
  { codigo: '16210', descripcion: 'Fabricación de madera laminada, terciada, enchapada y contrachapada, paneles para la construcción', sector: C },
  { codigo: '16220', descripcion: 'Fabricación de partes y piezas de carpintería para edificios y construcciones', sector: C },
  { codigo: '16230', descripcion: 'Fabricación de envases y recipientes de madera', sector: C },
  { codigo: '16292', descripcion: 'Fabricación de artesanías de madera, semillas, materiales trenzables', sector: C },
  { codigo: '16299', descripcion: 'Fabricación de productos de madera, corcho, paja y materiales trenzables ncp', sector: C },
  { codigo: '17010', descripcion: 'Fabricación de pasta de madera, papel y cartón', sector: C },
  { codigo: '17020', descripcion: 'Fabricación de papel y cartón ondulado y envases de papel y cartón', sector: C },
  { codigo: '17091', descripcion: 'Fabricación de artículos de papel y cartón de uso personal y doméstico', sector: C },
  { codigo: '17092', descripcion: 'Fabricación de productos de papel ncp', sector: C },
  { codigo: '18110', descripcion: 'Impresión', sector: C },
  { codigo: '18120', descripcion: 'Servicios relacionados con la impresión', sector: C },
  { codigo: '18200', descripcion: 'Reproducción de grabaciones', sector: C },
  { codigo: '19100', descripcion: 'Fabricación de productos de hornos de coque', sector: C },
  { codigo: '19201', descripcion: 'Fabricación de combustible', sector: C },
  { codigo: '19202', descripcion: 'Fabricación de aceites y lubricantes', sector: C },
  { codigo: '20111', descripcion: 'Fabricación de materias primas para la fabricación de colorantes', sector: C },
  { codigo: '20112', descripcion: 'Fabricación de materiales curtientes', sector: C },
  { codigo: '20113', descripcion: 'Fabricación de gases industriales', sector: C },
  { codigo: '20114', descripcion: 'Fabricación de alcohol etílico', sector: C },
  { codigo: '20119', descripcion: 'Fabricación de sustancias químicas básicas', sector: C },
  { codigo: '20120', descripcion: 'Fabricación de abonos y fertilizantes', sector: C },
  { codigo: '20130', descripcion: 'Fabricación de plástico y caucho en formas primarias', sector: C },
  { codigo: '20210', descripcion: 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario', sector: C },
  { codigo: '20220', descripcion: 'Fabricación de pinturas, barnices y productos de revestimiento similares; tintas de imprenta y masil as', sector: C },
  { codigo: '20231', descripcion: 'Fabricación de jabones, detergentes y similares para limpieza', sector: C },
  { codigo: '20232', descripcion: 'Fabricación de perfumes, cosméticos y productos de higiene y cuidado personal, incluyendo tintes, champú, etc.', sector: C },
  { codigo: '20291', descripcion: 'Fabricación de tintas y colores para escribir y pintar; fabricación de cintas para impresoras', sector: C },
  { codigo: '20292', descripcion: 'Fabricación de productos pirotécnicos, explosivos y municiones', sector: C },
  { codigo: '20299', descripcion: 'Fabricación de productos químicos n.c.p.', sector: C },
  { codigo: '20300', descripcion: 'Fabricación de fibras artificiales', sector: C },
  { codigo: '21001', descripcion: 'Manufactura de productos farmacéuticos, sustancias químicas y productos botánicos', sector: C },
  { codigo: '21008', descripcion: 'Maquilado de medicamentos', sector: C },
  { codigo: '22110', descripcion: 'Fabricación de cubiertas y cámaras; renovación y recauchutado de cubiertas', sector: C },
  { codigo: '22190', descripcion: 'Fabricación de otros productos de caucho', sector: C },
  { codigo: '22201', descripcion: 'Fabricación de envases plásticos', sector: C },
  { codigo: '22202', descripcion: 'Fabricación de productos plásticos para uso personal o doméstico', sector: C },
  { codigo: '22208', descripcion: 'Maquila de plásticos', sector: C },
  { codigo: '22209', descripcion: 'Fabricación de productos plásticos n.c.p.', sector: C },
  { codigo: '23101', descripcion: 'Fabricación de vidrio', sector: C },
  { codigo: '23102', descripcion: 'Fabricación de recipientes y envases de vidrio', sector: C },
  { codigo: '23108', descripcion: 'Servicio de maquilado', sector: C },
  { codigo: '23109', descripcion: 'Fabricación de productos de vidrio ncp', sector: C },
  { codigo: '23910', descripcion: 'Fabricación de productos refractarios', sector: C },
  { codigo: '23920', descripcion: 'Fabricación de productos de arcilla para la construcción', sector: C },
  { codigo: '23931', descripcion: 'Fabricación de productos de cerámica y porcelana no refractaria', sector: C },
  { codigo: '23932', descripcion: 'Fabricación de productos de cerámica y porcelana ncp', sector: C },
  { codigo: '23940', descripcion: 'Fabricación de cemento, cal y yeso', sector: C },
  { codigo: '23950', descripcion: 'Fabricación de artículos de hormigón, cemento y yeso', sector: C },
  { codigo: '23960', descripcion: 'Corte, tallado y acabado de la piedra', sector: C },
  { codigo: '23990', descripcion: 'Fabricación de productos minerales no metálicos ncp', sector: C },
  { codigo: '24100', descripcion: 'Industrias básicas de hierro y acero', sector: C },
  { codigo: '24200', descripcion: 'Fabricación de productos primarios de metales preciosos y metales no ferrosos', sector: C },
  { codigo: '24310', descripcion: 'Fundición de hierro y acero', sector: C },
  { codigo: '24320', descripcion: 'Fundición de metales no ferrosos', sector: C },
  { codigo: '25111', descripcion: 'Fabricación de productos metálicos para uso estructural', sector: C },
  { codigo: '25118', descripcion: 'Servicio de maquila para la fabricación de estructuras metálicas', sector: C },
  { codigo: '25120', descripcion: 'Fabricación de tanques, depósitos y recipientes de metal', sector: C },
  { codigo: '25130', descripcion: 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central', sector: C },
  { codigo: '25200', descripcion: 'Fabricación de armas y municiones', sector: C },
  { codigo: '25910', descripcion: 'Forjado, prensado, estampado y laminado de metales; pulvimetalurgia', sector: C },
  { codigo: '25920', descripcion: 'Tratamiento y revestimiento de metales', sector: C },
  { codigo: '25930', descripcion: 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería', sector: C },
  { codigo: '25991', descripcion: 'Fabricación de envases y artículos conexos de metal', sector: C },
  { codigo: '25992', descripcion: 'Fabricación de artículos metálicos de uso personal y/o doméstico', sector: C },
  { codigo: '25999', descripcion: 'Fabricación de productos elaborados de metal ncp', sector: C },
  { codigo: '26100', descripcion: 'Fabricación de componentes electrónicos', sector: C },
  { codigo: '26200', descripcion: 'Fabricación de computadoras y equipo conexo', sector: C },
  { codigo: '26300', descripcion: 'Fabricación de equipo de comunicaciones', sector: C },
  { codigo: '26400', descripcion: 'Fabricación de aparatos electrónicos de consumo para audio, video radio y televisión', sector: C },
  { codigo: '26510', descripcion: 'Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y de control de procesos industriales', sector: C },
  { codigo: '26520', descripcion: 'Fabricación de relojes y piezas de relojes', sector: C },
  { codigo: '26600', descripcion: 'Fabricación de equipo médico de irradiación y equipo electrónico de uso médico y terapéutico', sector: C },
  { codigo: '26700', descripcion: 'Fabricación de instrumentos de óptica y equipo fotográfico', sector: C },
  { codigo: '26800', descripcion: 'Fabricación de medios magnéticos y ópticos', sector: C },
  { codigo: '27100', descripcion: 'Fabricación de motores, generadores, transformadores eléctricos, aparatos de distribución y control de electricidad', sector: C },
  { codigo: '27200', descripcion: 'Fabricación de pilas, baterías y acumuladores', sector: C },
  { codigo: '27310', descripcion: 'Fabricación de cables de fibra óptica', sector: C },
  { codigo: '27320', descripcion: 'Fabricación de otros hilos y cables eléctricos', sector: C },
  { codigo: '27330', descripcion: 'Fabricación de dispositivos de cableados', sector: C },
  { codigo: '27400', descripcion: 'Fabricación de equipo eléctrico de iluminación', sector: C },
  { codigo: '27500', descripcion: 'Fabricación de aparatos de uso doméstico', sector: C },
  { codigo: '27900', descripcion: 'Fabricación de otros tipos de equipo eléctrico', sector: C },
  { codigo: '28110', descripcion: 'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas', sector: C },
  { codigo: '28120', descripcion: 'Fabricación de equipo hidráulico', sector: C },
  { codigo: '28130', descripcion: 'Fabricación de otras bombas, compresores, grifos y válvulas', sector: C },
  { codigo: '28140', descripcion: 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión', sector: C },
  { codigo: '28150', descripcion: 'Fabricación de hornos y quemadores', sector: C },
  { codigo: '28160', descripcion: 'Fabricación de equipo de elevación y manipulación', sector: C },
  { codigo: '28170', descripcion: 'Fabricación de maquinaria y equipo de oficina', sector: C },
  { codigo: '28180', descripcion: 'Fabricación de herramientas manuales', sector: C },
  { codigo: '28190', descripcion: 'Fabricación de otros tipos de maquinaria de uso general', sector: C },
  { codigo: '28210', descripcion: 'Fabricación de maquinaria agropecuaria y forestal', sector: C },
  { codigo: '28220', descripcion: 'Fabricación de máquinas para conformar metales y maquinaria herramienta', sector: C },
  { codigo: '28230', descripcion: 'Fabricación de maquinaria metalúrgica', sector: C },
  { codigo: '28240', descripcion: 'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción', sector: C },
  { codigo: '28250', descripcion: 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco', sector: C },
  { codigo: '28260', descripcion: 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros', sector: C },
  { codigo: '28291', descripcion: 'Fabricación de máquinas para imprenta', sector: C },
  { codigo: '28299', descripcion: 'Fabricación de maquinaria de uso especial ncp', sector: C },
  { codigo: '29100', descripcion: 'Fabricación vehículos automotores', sector: C },
  { codigo: '29200', descripcion: 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semiremolques', sector: C },
  { codigo: '29300', descripcion: 'Fabricación de partes, piezas y accesorios para vehículos automotores', sector: C },
  { codigo: '30110', descripcion: 'Fabricación de buques', sector: C },
  { codigo: '30120', descripcion: 'Construcción y reparación de embarcaciones de recreo', sector: C },
  { codigo: '30200', descripcion: 'Fabricación de locomotoras y de material rodante', sector: C },
  { codigo: '30300', descripcion: 'Fabricación de aeronaves y naves espaciales', sector: C },
  { codigo: '30400', descripcion: 'Fabricación de vehículos militares de combate', sector: C },
  { codigo: '30910', descripcion: 'Fabricación de motocicletas', sector: C },
  { codigo: '30920', descripcion: 'Fabricación de bicicletas y sillones de ruedas para inválidos', sector: C },
  { codigo: '30990', descripcion: 'Fabricación de equipo de transporte ncp', sector: C },
  { codigo: '31001', descripcion: 'Fabricación de colchones y somier', sector: C },
  { codigo: '31002', descripcion: 'Fabricación de muebles y otros productos de madera a medida', sector: C },
  { codigo: '31008', descripcion: 'Servicios de maquilado de muebles', sector: C },
  { codigo: '31009', descripcion: 'Fabricación de muebles ncp', sector: C },
  { codigo: '32110', descripcion: 'Fabricación de joyas platerías y joyerías', sector: C },
  { codigo: '32120', descripcion: 'Fabricación de joyas de imitación (fantasía) y artículos conexos', sector: C },
  { codigo: '32200', descripcion: 'Fabricación de instrumentos musicales', sector: C },
  { codigo: '32301', descripcion: 'Fabricación de artículos de deporte', sector: C },
  { codigo: '32308', descripcion: 'Servicio de maquila de productos deportivos', sector: C },
  { codigo: '32401', descripcion: 'Fabricación de juegos de mesa y de salón', sector: C },
  { codigo: '32402', descripcion: 'Servicio de maquilado de juguetes y juegos', sector: C },
  { codigo: '32409', descripcion: 'Fabricación de juegos y juguetes n.c.p.', sector: C },
  { codigo: '32500', descripcion: 'Fabricación de instrumentos y materiales médicos y odontológicos', sector: C },
  { codigo: '32901', descripcion: 'Fabricación de lápices, bolígrafos, sellos y artículos de librería en general', sector: C },
  { codigo: '32902', descripcion: 'Fabricación de escobas, cepillos, pinceles y similares', sector: C },
  { codigo: '32903', descripcion: 'Fabricación de artesanías de materiales diversos', sector: C },
  { codigo: '32904', descripcion: 'Fabricación de artículos de uso personal y domésticos n.c.p.', sector: C },
  { codigo: '32905', descripcion: 'Fabricación de accesorios para las confecciones y la marroquinería n.c.p.', sector: C },
  { codigo: '32908', descripcion: 'Servicios de maquila ncp', sector: C },
  { codigo: '32909', descripcion: 'Fabricación de productos manufacturados n.c.p.', sector: C },
  { codigo: '33110', descripcion: 'Reparación y mantenimiento de productos elaborados de metal', sector: C },
  { codigo: '33120', descripcion: 'Reparación y mantenimiento de maquinaria', sector: C },
  { codigo: '33130', descripcion: 'Reparación y mantenimiento de equipo electrónico y óptico', sector: C },
  { codigo: '33140', descripcion: 'Reparación y mantenimiento de equipo eléctrico', sector: C },
  { codigo: '33150', descripcion: 'Reparación y mantenimiento de equipo de transporte, excepto vehículos automotores', sector: C },
  { codigo: '33190', descripcion: 'Reparación y mantenimiento de equipos n.c.p.', sector: C },
  { codigo: '33200', descripcion: 'Instalación de maquinaria y equipo industrial', sector: C },

  // ── D · Suministro de electricidad, gas, vapor y aire acondicionado ───────
  { codigo: '35101', descripcion: 'Generación de energía eléctrica', sector: D },
  { codigo: '35102', descripcion: 'Transmisión de energía eléctrica', sector: D },
  { codigo: '35103', descripcion: 'Distribución de energía eléctrica', sector: D },
  { codigo: '35200', descripcion: 'Fabricación de gas, distribución de combustibles gaseosos por tuberías', sector: D },
  { codigo: '35300', descripcion: 'Suministro de vapor y agua caliente', sector: D },

  // ── E · Suministro de agua; alcantarillado, gestión de desechos ──────────
  { codigo: '36000', descripcion: 'Captación, tratamiento y suministro de agua', sector: E },
  { codigo: '37000', descripcion: 'Evacuación de aguas residuales (alcantarillado)', sector: E },
  { codigo: '38110', descripcion: 'Recolección y transporte de desechos sólidos proveniente de hogares y sector urbano', sector: E },
  { codigo: '38120', descripcion: 'Recolección de desechos peligrosos', sector: E },
  { codigo: '38210', descripcion: 'Tratamiento y eliminación de desechos inicuos', sector: E },
  { codigo: '38220', descripcion: 'Tratamiento y eliminación de desechos peligrosos', sector: E },
  { codigo: '38301', descripcion: 'Reciclaje de desperdicios y desechos textiles', sector: E },
  { codigo: '38302', descripcion: 'Reciclaje de desperdicios y desechos de plástico y caucho', sector: E },
  { codigo: '38303', descripcion: 'Reciclaje de desperdicios y desechos de vidrio', sector: E },
  { codigo: '38304', descripcion: 'Reciclaje de desperdicios y desechos de papel y cartón', sector: E },
  { codigo: '38305', descripcion: 'Reciclaje de desperdicios y desechos metálicos', sector: E },
  { codigo: '38309', descripcion: 'Reciclaje de desperdicios y desechos no metálicos n.c.p.', sector: E },
  { codigo: '39000', descripcion: 'Actividades de Saneamiento y otros Servicios de Gestión de Desechos', sector: E },

  // ── F · Construcción ─────────────────────────────────────────────────────
  { codigo: '41001', descripcion: 'Construcción de edificios residenciales', sector: F },
  { codigo: '41002', descripcion: 'Construcción de edificios no residenciales', sector: F },
  { codigo: '42100', descripcion: 'Construcción de carreteras, calles y caminos', sector: F },
  { codigo: '42200', descripcion: 'Construcción de proyectos de servicio público', sector: F },
  { codigo: '42900', descripcion: 'Construcción de obras de ingeniería civil n.c.p.', sector: F },
  { codigo: '43110', descripcion: 'Demolición', sector: F },
  { codigo: '43120', descripcion: 'Preparación de terreno', sector: F },
  { codigo: '43210', descripcion: 'Instalaciones eléctricas', sector: F },
  { codigo: '43220', descripcion: 'Instalación de fontanería, calefacción y aire acondicionado', sector: F },
  { codigo: '43290', descripcion: 'Otras instalaciones para obras de construcción', sector: F },
  { codigo: '43300', descripcion: 'Terminación y acabado de edificios', sector: F },
  { codigo: '43900', descripcion: 'Otras actividades especializadas de construcción', sector: F },
  { codigo: '43901', descripcion: 'Fabricación de techos y materiales diversos', sector: F },

  // ── G · Comercio al por mayor y al por menor ─────────────────────────────
  { codigo: '45100', descripcion: 'Venta de vehículos automotores', sector: G },
  { codigo: '45201', descripcion: 'Reparación mecánica de vehículos automotores', sector: G },
  { codigo: '45202', descripcion: 'Reparaciones eléctricas del automotor y recarga de baterías', sector: G },
  { codigo: '45203', descripcion: 'Enderezado y pintura de vehículos automotores', sector: G },
  { codigo: '45204', descripcion: 'Reparaciones de radiadores, escapes y silenciadores', sector: G },
  { codigo: '45205', descripcion: 'Reparación y reconstrucción de vías, stop y otros artículos de fibra de vidrio', sector: G },
  { codigo: '45206', descripcion: 'Reparación de llantas de vehículos automotores', sector: G },
  { codigo: '45207', descripcion: 'Polarizado de vehículos (mediante la adhesión de papel especial a los vidrios)', sector: G },
  { codigo: '45208', descripcion: 'Lavado y pasteado de vehículos (carwash)', sector: G },
  { codigo: '45209', descripcion: 'Reparaciones de vehículos n.c.p.', sector: G },
  { codigo: '45211', descripcion: 'Remolque de vehículos automotores', sector: G },
  { codigo: '45301', descripcion: 'Venta de partes, piezas y accesorios nuevos para vehículos automotores', sector: G },
  { codigo: '45302', descripcion: 'Venta de partes, piezas y accesorios usados para vehículos automotores', sector: G },
  { codigo: '45401', descripcion: 'Venta de motocicletas', sector: G },
  { codigo: '45402', descripcion: 'Venta de repuestos, piezas y accesorios de motocicletas', sector: G },
  { codigo: '45403', descripcion: 'Mantenimiento y reparación de motocicletas', sector: G },
  { codigo: '46100', descripcion: 'Venta al por mayor a cambio de retribución o por contrata', sector: G },
  { codigo: '46201', descripcion: 'Venta al por mayor de materias primas agrícolas', sector: G },
  { codigo: '46202', descripcion: 'Venta al por mayor de productos de la silvicultura', sector: G },
  { codigo: '46203', descripcion: 'Venta al por mayor de productos pecuarios y de granja', sector: G },
  { codigo: '46211', descripcion: 'Venta de productos para uso agropecuario', sector: G },
  { codigo: '46291', descripcion: 'Venta al por mayor de granos básicos (cereales, leguminosas)', sector: G },
  { codigo: '46292', descripcion: 'Venta al por mayor de semillas mejoradas para cultivo', sector: G },
  { codigo: '46293', descripcion: 'Venta al por mayor de café oro y uva', sector: G },
  { codigo: '46294', descripcion: 'Venta al por mayor de caña de azúcar', sector: G },
  { codigo: '46295', descripcion: 'Venta al por mayor de flores, plantas y otros productos naturales', sector: G },
  { codigo: '46296', descripcion: 'Venta al por mayor de productos agrícolas', sector: G },
  { codigo: '46297', descripcion: 'Venta al por mayor de ganado bovino (vivo)', sector: G },
  { codigo: '46298', descripcion: 'Venta al por mayor de animales porcinos, ovinos, caprino, canículas, apícolas, avícolas vivos', sector: G },
  { codigo: '46299', descripcion: 'Venta de otras especies vivas del reino animal', sector: G },
  { codigo: '46301', descripcion: 'Venta al por mayor de alimentos', sector: G },
  { codigo: '46302', descripcion: 'Venta al por mayor de bebidas', sector: G },
  { codigo: '46303', descripcion: 'Venta al por mayor de tabaco', sector: G },
  { codigo: '46371', descripcion: 'Venta al por mayor de frutas, hortalizas (verduras), legumbres y tubérculos', sector: G },
  { codigo: '46372', descripcion: 'Venta al por mayor de pollos, gallinas destazadas, pavos y otras aves', sector: G },
  { codigo: '46373', descripcion: 'Venta al por mayor de carne bovina y porcina, productos de carne y embutidos', sector: G },
  { codigo: '46374', descripcion: 'Venta al por mayor de huevos', sector: G },
  { codigo: '46375', descripcion: 'Venta al por mayor de productos lácteos', sector: G },
  { codigo: '46376', descripcion: 'Venta al por mayor de productos farináceos de panadería (pan dulce, cakes, repostería, etc.)', sector: G },
  { codigo: '46377', descripcion: 'Venta al por mayor de pastas alimenticias, aceites y grasas comestibles vegetal y animal', sector: G },
  { codigo: '46378', descripcion: 'Venta al por mayor de sal comestible', sector: G },
  { codigo: '46379', descripcion: 'Venta al por mayor de azúcar', sector: G },
  { codigo: '46391', descripcion: 'Venta al por mayor de abarrotes (vinos, licores, productos alimenticios envasados, etc.)', sector: G },
  { codigo: '46392', descripcion: 'Venta al por mayor de aguas gaseosas', sector: G },
  { codigo: '46393', descripcion: 'Venta al por mayor de agua purificada', sector: G },
  { codigo: '46394', descripcion: 'Venta al por mayor de refrescos y otras bebidas, líquidas o en polvo', sector: G },
  { codigo: '46395', descripcion: 'Venta al por mayor de cerveza y licores', sector: G },
  { codigo: '46396', descripcion: 'Venta al por mayor de hielo', sector: G },
  { codigo: '46411', descripcion: 'Venta al por mayor de hilados, tejidos y productos textiles de mercería', sector: G },
  { codigo: '46412', descripcion: 'Venta al por mayor de artículos textiles excepto confecciones para el hogar', sector: G },
  { codigo: '46413', descripcion: 'Venta al por mayor de confecciones textiles para el hogar', sector: G },
  { codigo: '46414', descripcion: 'Venta al por mayor de prendas de vestir y accesorios de vestir', sector: G },
  { codigo: '46415', descripcion: 'Venta al por mayor de ropa usada', sector: G },
  { codigo: '46416', descripcion: 'Venta al por mayor de calzado', sector: G },
  { codigo: '46417', descripcion: 'Venta al por mayor de artículos de marroquinería y talabartería', sector: G },
  { codigo: '46418', descripcion: 'Venta al por mayor de artículos de peletería', sector: G },
  { codigo: '46419', descripcion: 'Venta al por mayor de otros artículos textiles n.c.p.', sector: G },
  { codigo: '46471', descripcion: 'Venta al por mayor de instrumentos musicales', sector: G },
  { codigo: '46472', descripcion: 'Venta al por mayor de colchones, almohadas, cojines, etc.', sector: G },
  { codigo: '46473', descripcion: 'Venta al por mayor de artículos de aluminio para el hogar y para otros usos', sector: G },
  { codigo: '46474', descripcion: 'Venta al por mayor de depósitos y otros artículos plásticos para el hogar y otros usos, incluyendo los desechables de durapax y no desechables', sector: G },
  { codigo: '46475', descripcion: 'Venta al por mayor de cámaras fotográficas, accesorios y materiales', sector: G },
  { codigo: '46482', descripcion: 'Venta al por mayor de medicamentos, artículos y otros productos de uso veterinario', sector: G },
  { codigo: '46483', descripcion: 'Venta al por mayor de productos y artículos de belleza y de uso personal', sector: G },
  { codigo: '46484', descripcion: 'Venta de productos farmacéuticos y medicinales', sector: G },
  { codigo: '46491', descripcion: 'Venta al por mayor de productos medicinales, cosméticos, perfumería y productos de limpieza', sector: G },
  { codigo: '46492', descripcion: 'Venta al por mayor de relojes y artículos de joyería', sector: G },
  { codigo: '46493', descripcion: 'Venta al por mayor de electrodomésticos y artículos del hogar excepto bazar; artículos de iluminación', sector: G },
  { codigo: '46494', descripcion: 'Venta al por mayor de artículos de bazar y similares', sector: G },
  { codigo: '46495', descripcion: 'Venta al por mayor de artículos de óptica', sector: G },
  { codigo: '46496', descripcion: 'Venta al por mayor de revistas, periódicos, libros, artículos de librería y artículos de papel y cartón en general', sector: G },
  { codigo: '46497', descripcion: 'Venta de artículos deportivos, juguetes y rodados', sector: G },
  { codigo: '46498', descripcion: 'Venta al por mayor de productos usados para el hogar o el uso personal', sector: G },
  { codigo: '46499', descripcion: 'Venta al por mayor de enseres domésticos y de uso personal n.c.p.', sector: G },
  { codigo: '46500', descripcion: 'Venta al por mayor de bicicletas, partes, accesorios y otros', sector: G },
  { codigo: '46510', descripcion: 'Venta al por mayor de computadoras, equipo periférico y programas informáticos', sector: G },
  { codigo: '46520', descripcion: 'Venta al por mayor de equipos de comunicación', sector: G },
  { codigo: '46530', descripcion: 'Venta al por mayor de maquinaria y equipo agropecuario, accesorios, partes y suministros', sector: G },
  { codigo: '46590', descripcion: 'Venta de equipos e instrumentos de uso profesional y científico y aparatos de medida y control', sector: G },
  { codigo: '46591', descripcion: 'Venta al por mayor de maquinaria equipo, accesorios y materiales para la industria de la madera y sus productos', sector: G },
  { codigo: '46592', descripcion: 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria gráfica y del papel, cartón y productos de papel y cartón', sector: G },
  { codigo: '46593', descripcion: 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria de productos químicos, plástico y caucho', sector: G },
  { codigo: '46594', descripcion: 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria metálica y de sus productos', sector: G },
  { codigo: '46595', descripcion: 'Venta al por mayor de equipamiento para uso médico, odontológico, veterinario y servicios conexos', sector: G },
  { codigo: '46596', descripcion: 'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria de la alimentación', sector: G },
  { codigo: '46597', descripcion: 'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria textil, confecciones y cuero', sector: G },
  { codigo: '46598', descripcion: 'Venta al por mayor de maquinaria, equipo y accesorios para la construcción y explotación de minas y canteras', sector: G },
  { codigo: '46599', descripcion: 'Venta al por mayor de otro tipo de maquinaria y equipo con sus accesorios y partes', sector: G },
  { codigo: '46610', descripcion: 'Venta al por mayor de otros combustibles sólidos, líquidos, gaseosos y de productos conexos', sector: G },
  { codigo: '46612', descripcion: 'Venta al por mayor de combustibles para automotores, aviones, barcos, maquinaria y otros', sector: G },
  { codigo: '46613', descripcion: 'Venta al por mayor de lubricantes, grasas y otros aceites para automotores, maquinaria industrial, etc.', sector: G },
  { codigo: '46614', descripcion: 'Venta al por mayor de gas propano', sector: G },
  { codigo: '46615', descripcion: 'Venta al por mayor de leña y carbón', sector: G },
  { codigo: '46620', descripcion: 'Venta al por mayor de metales y minerales metalíferos', sector: G },
  { codigo: '46631', descripcion: 'Venta al por mayor de puertas, ventanas, vitrinas y similares', sector: G },
  { codigo: '46632', descripcion: 'Venta al por mayor de artículos de ferretería y pinturerías', sector: G },
  { codigo: '46633', descripcion: 'Vidrierías', sector: G },
  { codigo: '46634', descripcion: 'Venta al por mayor de maderas', sector: G },
  { codigo: '46639', descripcion: 'Venta al por mayor de materiales para la construcción n.c.p.', sector: G },
  { codigo: '46691', descripcion: 'Venta al por mayor de sal industrial sin yodar', sector: G },
  { codigo: '46692', descripcion: 'Venta al por mayor de productos intermedios y desechos de origen textil', sector: G },
  { codigo: '46693', descripcion: 'Venta al por mayor de productos intermedios y desechos de origen metálico', sector: G },
  { codigo: '46694', descripcion: 'Venta al por mayor de productos intermedios y desechos de papel y cartón', sector: G },
  { codigo: '46695', descripcion: 'Venta al por mayor fertilizantes, abonos, agroquímicos y productos similares', sector: G },
  { codigo: '46696', descripcion: 'Venta al por mayor de productos intermedios y desechos de origen plástico', sector: G },
  { codigo: '46697', descripcion: 'Venta al por mayor de tintas para imprenta, productos curtientes y materias y productos colorantes', sector: G },
  { codigo: '46698', descripcion: 'Venta de productos intermedios y desechos de origen químico y de caucho', sector: G },
  { codigo: '46699', descripcion: 'Venta al por mayor de productos intermedios y desechos ncp', sector: G },
  { codigo: '46701', descripcion: 'Venta de algodón en oro', sector: G },
  { codigo: '46900', descripcion: 'Venta al por mayor de otros productos', sector: G },
  { codigo: '46901', descripcion: 'Venta al por mayor de cohetes y otros productos pirotécnicos', sector: G },
  { codigo: '46902', descripcion: 'Venta al por mayor de artículos diversos para consumo humano', sector: G },
  { codigo: '46903', descripcion: 'Venta al por mayor de armas de fuego, municiones y accesorios', sector: G },
  { codigo: '46904', descripcion: 'Venta al por mayor de toldos y tiendas de campaña de cualquier material', sector: G },
  { codigo: '46905', descripcion: 'Venta al por mayor de exhibidores publicitarios y rótulos', sector: G },
  { codigo: '46906', descripcion: 'Venta al por mayor de artículos promocionales diversos', sector: G },
  { codigo: '47111', descripcion: 'Venta en supermercados', sector: G },
  { codigo: '47112', descripcion: 'Venta en tiendas de artículos de primera necesidad', sector: G },
  { codigo: '47119', descripcion: 'Almacenes (venta de diversos artículos)', sector: G },
  { codigo: '47190', descripcion: 'Venta al por menor de otros productos en comercios no especializados', sector: G },
  { codigo: '47199', descripcion: 'Venta de establecimientos no especializados con surtido compuesto principalmente de alimentos, bebidas y tabaco', sector: G },
  { codigo: '47211', descripcion: 'Venta al por menor de frutas y hortalizas', sector: G },
  { codigo: '47212', descripcion: 'Venta al por menor de carnes, embutidos y productos de granja', sector: G },
  { codigo: '47213', descripcion: 'Venta al por menor de pescado y mariscos', sector: G },
  { codigo: '47214', descripcion: 'Venta al por menor de productos lácteos', sector: G },
  { codigo: '47215', descripcion: 'Venta al por menor de productos de panadería, repostería y galletas', sector: G },
  { codigo: '47216', descripcion: 'Venta al por menor de huevos', sector: G },
  { codigo: '47217', descripcion: 'Venta al por menor de carnes y productos cárnicos', sector: G },
  { codigo: '47218', descripcion: 'Venta al por menor de granos básicos y otros', sector: G },
  { codigo: '47219', descripcion: 'Venta al por menor de alimentos n.c.p.', sector: G },
  { codigo: '47221', descripcion: 'Venta al por menor de hielo', sector: G },
  { codigo: '47223', descripcion: 'Venta de bebidas no alcohólicas, para su consumo fuera del establecimiento', sector: G },
  { codigo: '47224', descripcion: 'Venta de bebidas alcohólicas, para su consumo fuera del establecimiento', sector: G },
  { codigo: '47225', descripcion: 'Venta de bebidas alcohólicas para su consumo dentro del establecimiento', sector: G },
  { codigo: '47230', descripcion: 'Venta al por menor de tabaco', sector: G },
  { codigo: '47300', descripcion: 'Venta de combustibles, lubricantes y otros (gasolineras)', sector: G },
  { codigo: '47411', descripcion: 'Venta al por menor de computadoras y equipo periférico', sector: G },
  { codigo: '47412', descripcion: 'Venta de equipo y accesorios de telecomunicación', sector: G },
  { codigo: '47420', descripcion: 'Venta al por menor de equipo de audio y video', sector: G },
  { codigo: '47510', descripcion: 'Venta al por menor de hilados, tejidos y productos textiles de mercería; confecciones para el hogar y textiles n.c.p.', sector: G },
  { codigo: '47521', descripcion: 'Venta al por menor de productos de madera', sector: G },
  { codigo: '47522', descripcion: 'Venta al por menor de artículos de ferretería', sector: G },
  { codigo: '47523', descripcion: 'Venta al por menor de productos de pinturerías', sector: G },
  { codigo: '47524', descripcion: 'Venta al por menor en vidrierías', sector: G },
  { codigo: '47529', descripcion: 'Venta al por menor de materiales de construcción y artículos conexos', sector: G },
  { codigo: '47530', descripcion: 'Venta al por menor de tapices, alfombras y revestimientos de paredes y pisos en comercios especializados', sector: G },
  { codigo: '47591', descripcion: 'Venta al por menor de muebles', sector: G },
  { codigo: '47592', descripcion: 'Venta al por menor de artículos de bazar', sector: G },
  { codigo: '47593', descripcion: 'Venta al por menor de aparatos electrodomésticos, repuestos y accesorios', sector: G },
  { codigo: '47594', descripcion: 'Venta al por menor de artículos eléctricos y de iluminación', sector: G },
  { codigo: '47598', descripcion: 'Venta al por menor de instrumentos musicales', sector: G },
  { codigo: '47610', descripcion: 'Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados', sector: G },
  { codigo: '47620', descripcion: 'Venta al por menor de discos láser, cassettes, cintas de video y otros', sector: G },
  { codigo: '47630', descripcion: 'Venta al por menor de productos y equipos de deporte', sector: G },
  { codigo: '47631', descripcion: 'Venta al por menor de bicicletas, accesorios y repuestos', sector: G },
  { codigo: '47640', descripcion: 'Venta al por menor de juegos y juguetes en comercios especializados', sector: G },
  { codigo: '47711', descripcion: 'Venta al por menor de prendas de vestir y accesorios de vestir', sector: G },
  { codigo: '47712', descripcion: 'Venta al por menor de calzado', sector: G },
  { codigo: '47713', descripcion: 'Venta al por menor de artículos de peletería, marroquinería y talabartería', sector: G },
  { codigo: '47721', descripcion: 'Venta al por menor de medicamentos farmacéuticos y otros materiales y artículos de uso médico, odontológico y veterinario', sector: G },
  { codigo: '47722', descripcion: 'Venta al por menor de productos cosméticos y de tocador', sector: G },
  { codigo: '47731', descripcion: 'Venta al por menor de productos de joyería, bisutería, óptica, relojería', sector: G },
  { codigo: '47732', descripcion: 'Venta al por menor de plantas, semillas, animales y artículos conexos', sector: G },
  { codigo: '47733', descripcion: 'Venta al por menor de combustibles de uso doméstico (gas propano y gas licuado)', sector: G },
  { codigo: '47734', descripcion: 'Venta al por menor de artesanías, artículos cerámicos y recuerdos en general', sector: G },
  { codigo: '47735', descripcion: 'Venta al por menor de ataúdes, lápidas y cruces, trofeos, artículos religiosos en general', sector: G },
  { codigo: '47736', descripcion: 'Venta al por menor de armas de fuego, municiones y accesorios', sector: G },
  { codigo: '47737', descripcion: 'Venta al por menor de artículos de cohetería y pirotécnicos', sector: G },
  { codigo: '47738', descripcion: 'Venta al por menor de artículos desechables de uso personal y doméstico (servilletas, papel higiénico, pañales, toallas sanitarias, etc.)', sector: G },
  { codigo: '47739', descripcion: 'Venta al por menor de otros productos n.c.p.', sector: G },
  { codigo: '47741', descripcion: 'Venta al por menor de artículos usados', sector: G },
  { codigo: '47742', descripcion: 'Venta al por menor de textiles y confecciones usados', sector: G },
  { codigo: '47743', descripcion: 'Venta al por menor de libros, revistas, papel y cartón usados', sector: G },
  { codigo: '47749', descripcion: 'Venta al por menor de productos usados n.c.p.', sector: G },
  { codigo: '47811', descripcion: 'Venta al por menor de frutas, verduras y hortalizas', sector: G },
  { codigo: '47814', descripcion: 'Venta al por menor de productos lácteos', sector: G },
  { codigo: '47815', descripcion: 'Venta al por menor de productos de panadería, galletas y similares', sector: G },
  { codigo: '47816', descripcion: 'Venta al por menor de bebidas', sector: G },
  { codigo: '47818', descripcion: 'Venta al por menor en tiendas de mercado y puestos', sector: G },
  { codigo: '47821', descripcion: 'Venta al por menor de hilados, tejidos y productos textiles de mercería en puestos de mercados y ferias', sector: G },
  { codigo: '47822', descripcion: 'Venta al por menor de artículos textiles excepto confecciones para el hogar en puestos de mercados y ferias', sector: G },
  { codigo: '47823', descripcion: 'Venta al por menor de confecciones textiles para el hogar en puestos de mercados y ferias', sector: G },
  { codigo: '47824', descripcion: 'Venta al por menor de prendas de vestir, accesorios de vestir y similares en puestos de mercados y ferias', sector: G },
  { codigo: '47825', descripcion: 'Venta al por menor de ropa usada', sector: G },
  { codigo: '47826', descripcion: 'Venta al por menor de calzado, artículos de marroquinería y talabartería en puestos de mercados y ferias', sector: G },
  { codigo: '47827', descripcion: 'Venta al por menor de artículos de marroquinería y talabartería en puestos de mercados y ferias', sector: G },
  { codigo: '47829', descripcion: 'Venta al por menor de artículos textiles ncp en puestos de mercados y ferias', sector: G },
  { codigo: '47891', descripcion: 'Venta al por menor de animales, flores y productos conexos en puestos de feria y mercados', sector: G },
  { codigo: '47892', descripcion: 'Venta al por menor de productos medicinales, cosméticos, de tocador y de limpieza en puestos de ferias y mercados', sector: G },
  { codigo: '47893', descripcion: 'Venta al por menor de artículos de bazar en puestos de ferias y mercados', sector: G },
  { codigo: '47894', descripcion: 'Venta al por menor de artículos de papel, envases, libros, revistas y conexos en puestos de feria y mercados', sector: G },
  { codigo: '47895', descripcion: 'Venta al por menor de materiales de construcción, electrodomésticos, accesorios para autos y similares en puestos de feria y mercados', sector: G },
  { codigo: '47896', descripcion: 'Venta al por menor de equipos accesorios para las comunicaciones en puestos de feria y mercados', sector: G },
  { codigo: '47899', descripcion: 'Venta al por menor en puestos de ferias y mercados n.c.p.', sector: G },
  { codigo: '47910', descripcion: 'Venta al por menor por correo o Internet', sector: G },
  { codigo: '47990', descripcion: 'Otros tipos de venta al por menor no realizada, en almacenes,', sector: G },

  // ── H · Transporte y almacenamiento ──────────────────────────────────────
  { codigo: '49110', descripcion: 'Transporte interurbano de pasajeros por ferrocarril', sector: H },
  { codigo: '49120', descripcion: 'Transporte de carga por ferrocarril', sector: H },
  { codigo: '49211', descripcion: 'Transporte de pasajeros urbanos e interurbano mediante buses', sector: H },
  { codigo: '49212', descripcion: 'Transporte de pasajeros interdepartamental mediante microbuses', sector: H },
  { codigo: '49213', descripcion: 'Transporte de pasajeros urbanos e interurbano mediante microbuses', sector: H },
  { codigo: '49214', descripcion: 'Transporte de pasajeros interdepartamental mediante buses', sector: H },
  { codigo: '49221', descripcion: 'Transporte internacional de pasajeros', sector: H },
  { codigo: '49222', descripcion: 'Transporte de pasajeros mediante taxis y autos con chofer', sector: H },
  { codigo: '49223', descripcion: 'Transporte escolar', sector: H },
  { codigo: '49225', descripcion: 'Transporte de pasajeros para excursiones', sector: H },
  { codigo: '49226', descripcion: 'Servicios de transporte de personal', sector: H },
  { codigo: '49229', descripcion: 'Transporte de pasajeros por vía terrestre ncp', sector: H },
  { codigo: '49231', descripcion: 'Transporte de carga urbano', sector: H },
  { codigo: '49232', descripcion: 'Transporte nacional de carga', sector: H },
  { codigo: '49233', descripcion: 'Transporte de carga internacional', sector: H },
  { codigo: '49234', descripcion: 'Servicios de mudanza', sector: H },
  { codigo: '49235', descripcion: 'Alquiler de vehículos de carga con conductor', sector: H },
  { codigo: '49300', descripcion: 'Transporte por oleoducto o gasoducto', sector: H },
  { codigo: '50110', descripcion: 'Transporte de pasajeros marítimo y de cabotaje', sector: H },
  { codigo: '50120', descripcion: 'Transporte de carga marítimo y de cabotaje', sector: H },
  { codigo: '50211', descripcion: 'Transporte de pasajeros por vías de navegación interiores', sector: H },
  { codigo: '50212', descripcion: 'Alquiler de equipo de transporte de pasajeros por vías de navegación interior con conductor', sector: H },
  { codigo: '50220', descripcion: 'Transporte de carga por vías de navegación interiores', sector: H },
  { codigo: '51100', descripcion: 'Transporte aéreo de pasajeros', sector: H },
  { codigo: '51201', descripcion: 'Transporte de carga por vía aérea', sector: H },
  { codigo: '51202', descripcion: 'Alquiler de equipo de aerotransporte con operadores para el propósito de transportar carga', sector: H },
  { codigo: '52101', descripcion: 'Alquiler de instalaciones de almacenamiento en zonas francas', sector: H },
  { codigo: '52102', descripcion: 'Alquiler de silos para conservación y almacenamiento de granos', sector: H },
  { codigo: '52103', descripcion: 'Alquiler de instalaciones con refrigeración para almacenamiento y conservación de alimentos y otros productos', sector: H },
  { codigo: '52109', descripcion: 'Alquiler de bodegas para almacenamiento y depósito n.c.p.', sector: H },
  { codigo: '52211', descripcion: 'Servicio de garaje y estacionamiento', sector: H },
  { codigo: '52212', descripcion: 'Servicios de terminales para el transporte por vía terrestre', sector: H },
  { codigo: '52219', descripcion: 'Servicios para el transporte por vía terrestre n.c.p.', sector: H },
  { codigo: '52220', descripcion: 'Servicios para el transporte acuático', sector: H },
  { codigo: '52230', descripcion: 'Servicios para el transporte aéreo', sector: H },
  { codigo: '52240', descripcion: 'Manipulación de carga', sector: H },
  { codigo: '52290', descripcion: 'Servicios para el transporte ncp', sector: H },
  { codigo: '52291', descripcion: 'Agencias de tramitaciones aduanales', sector: H },
  { codigo: '53100', descripcion: 'Servicios de correo nacional', sector: H },
  { codigo: '53200', descripcion: 'Actividades de correo distintas a las actividades postales nacionales', sector: H },

  // ── I · Actividades de alojamiento y de servicio de comidas ──────────────
  { codigo: '55101', descripcion: 'Actividades de alojamiento para estancias cortas', sector: I },
  { codigo: '55102', descripcion: 'Hoteles', sector: I },
  { codigo: '55200', descripcion: 'Actividades de campamentos, parques de vehículos de recreo y parques de caravanas', sector: I },
  { codigo: '55900', descripcion: 'Alojamiento n.c.p.', sector: I },
  { codigo: '56101', descripcion: 'Restaurantes', sector: I },
  { codigo: '56106', descripcion: 'Pupusería', sector: I },
  { codigo: '56107', descripcion: 'Actividades varias de restaurantes', sector: I },
  { codigo: '56108', descripcion: 'Comedores', sector: I },
  { codigo: '56109', descripcion: 'Merenderos ambulantes', sector: I },
  { codigo: '56210', descripcion: 'Preparación de comida para eventos especiales', sector: I },
  { codigo: '56291', descripcion: 'Servicios de provisión de comidas por contrato', sector: I },
  { codigo: '56292', descripcion: 'Servicios de concesión de cafetines y chalet en empresas e instituciones', sector: I },
  { codigo: '56299', descripcion: 'Servicios de preparación de comidas ncp', sector: I },
  { codigo: '56301', descripcion: 'Servicio de expendio de bebidas en salones y bares', sector: I },
  { codigo: '56302', descripcion: 'Servicio de expendio de bebidas en puestos callejeros, mercados y ferias', sector: I },

  // ── J · Información y comunicaciones ──────────────────────────────────────
  { codigo: '58110', descripcion: 'Edición de libros, folletos, partituras y otras ediciones distintas a estas', sector: J },
  { codigo: '58120', descripcion: 'Edición de directorios y listas de correos', sector: J },
  { codigo: '58130', descripcion: 'Edición de periódicos, revistas y otras publicaciones periódicas', sector: J },
  { codigo: '58190', descripcion: 'Otras actividades de edición', sector: J },
  { codigo: '58200', descripcion: 'Edición de programas informáticos (software)', sector: J },
  { codigo: '59110', descripcion: 'Actividades de producción cinematográfica', sector: J },
  { codigo: '59120', descripcion: 'Actividades de post producción de películas, videos y programas de televisión', sector: J },
  { codigo: '59130', descripcion: 'Actividades de distribución de películas cinematográficas, videos y programas de televisión', sector: J },
  { codigo: '59140', descripcion: 'Actividades de exhibición de películas cinematográficas y cintas de vídeo', sector: J },
  { codigo: '59200', descripcion: 'Actividades de edición y grabación de música', sector: J },
  { codigo: '60100', descripcion: 'Servicios de difusiones de radio', sector: J },
  { codigo: '60201', descripcion: 'Actividades de programación y difusión de televisión abierta', sector: J },
  { codigo: '60202', descripcion: 'Actividades de suscripción y difusión de televisión por cable y/o suscripción', sector: J },
  { codigo: '60299', descripcion: 'Servicios de televisión, incluye televisión por cable', sector: J },
  { codigo: '60900', descripcion: 'Programación y transmisión de radio y televisión', sector: J },
  { codigo: '61101', descripcion: 'Servicio de telefonía', sector: J },
  { codigo: '61102', descripcion: 'Servicio de Internet', sector: J },
  { codigo: '61103', descripcion: 'Servicio de telefonía fija', sector: J },
  { codigo: '61109', descripcion: 'Servicio de Internet n.c.p.', sector: J },
  { codigo: '61201', descripcion: 'Servicios de telefonía celular', sector: J },
  { codigo: '61202', descripcion: 'Servicios de Internet inalámbrico', sector: J },
  { codigo: '61209', descripcion: 'Servicios de telecomunicaciones inalámbrico n.c.p.', sector: J },
  { codigo: '61301', descripcion: 'Telecomunicaciones satelitales', sector: J },
  { codigo: '61309', descripcion: 'Comunicación vía satélite n.c.p.', sector: J },
  { codigo: '61900', descripcion: 'Actividades de telecomunicación n.c.p.', sector: J },
  { codigo: '62010', descripcion: 'Programación informática', sector: J },
  { codigo: '62020', descripcion: 'Consultorías y gestión de servicios informáticos', sector: J },
  { codigo: '62090', descripcion: 'Otras actividades de tecnología de información y servicios de computadora', sector: J },
  { codigo: '63110', descripcion: 'Procesamiento de datos y actividades relacionadas', sector: J },
  { codigo: '63120', descripcion: 'Portales WEB', sector: J },
  { codigo: '63910', descripcion: 'Servicios de Agencias de Noticias', sector: J },
  { codigo: '63990', descripcion: 'Otros servicios de información n.c.p.', sector: J },

  // ── K · Actividades financieras y de seguros ──────────────────────────────
  { codigo: '64110', descripcion: 'Servicios provistos por el Banco Central de El salvador', sector: K },
  { codigo: '64190', descripcion: 'Bancos', sector: K },
  { codigo: '64192', descripcion: 'Entidades dedicadas al envío de remesas', sector: K },
  { codigo: '64199', descripcion: 'Otras entidades financieras', sector: K },
  { codigo: '64200', descripcion: 'Actividades de sociedades de cartera', sector: K },
  { codigo: '64300', descripcion: 'Fideicomisos, fondos y otras fuentes de financiamiento', sector: K },
  { codigo: '64910', descripcion: 'Arrendamientos financieros', sector: K },
  { codigo: '64920', descripcion: 'Asociaciones cooperativas de ahorro y crédito dedicadas a la intermediación financiera', sector: K },
  { codigo: '64921', descripcion: 'Instituciones emisoras de tarjetas de crédito y otros', sector: K },
  { codigo: '64922', descripcion: 'Tipos de crédito ncp', sector: K },
  { codigo: '64928', descripcion: 'Prestamistas y casas de empeño', sector: K },
  { codigo: '64990', descripcion: 'Actividades de servicios financieros, excepto la financiación de planes de seguros y de pensiones n.c.p.', sector: K },
  { codigo: '65110', descripcion: 'Planes de seguros de vida', sector: K },
  { codigo: '65120', descripcion: 'Planes de seguro excepto de vida', sector: K },
  { codigo: '65199', descripcion: 'Seguros generales de todo tipo', sector: K },
  { codigo: '65200', descripcion: 'Planes se seguro', sector: K },
  { codigo: '65300', descripcion: 'Planes de pensiones', sector: K },
  { codigo: '66110', descripcion: 'Administración de mercados financieros (Bolsa de Valores)', sector: K },
  { codigo: '66120', descripcion: 'Actividades bursátiles (Corredores de Bolsa)', sector: K },
  { codigo: '66190', descripcion: 'Actividades auxiliares de la intermediación financiera ncp', sector: K },
  { codigo: '66210', descripcion: 'Evaluación de riesgos y daños', sector: K },
  { codigo: '66220', descripcion: 'Actividades de agentes y corredores de seguros', sector: K },
  { codigo: '66290', descripcion: 'Otras actividades auxiliares de seguros y fondos de pensiones', sector: K },
  { codigo: '66300', descripcion: 'Actividades de administración de fondos', sector: K },

  // ── L · Actividades inmobiliarias ─────────────────────────────────────────
  { codigo: '68101', descripcion: 'Servicio de alquiler y venta de lotes en cementerios', sector: L },
  { codigo: '68109', descripcion: 'Actividades inmobiliarias realizadas con bienes propios o arrendados n.c.p.', sector: L },
  { codigo: '68200', descripcion: 'Actividades Inmobiliarias Realizadas a Cambio de una Retribución o por Contrata', sector: L },

  // ── M · Actividades profesionales, científicas y técnicas ─────────────────
  { codigo: '69100', descripcion: 'Actividades jurídicas', sector: M },
  { codigo: '69200', descripcion: 'Actividades de contabilidad, teneduría de libros y auditoría; asesoramiento en materia de impuestos', sector: M },
  { codigo: '70100', descripcion: 'Actividades de oficinas centrales de sociedades de cartera', sector: M },
  { codigo: '70200', descripcion: 'Actividades de consultoría en gestión empresarial', sector: M },
  { codigo: '71101', descripcion: 'Servicios de arquitectura y planificación urbana y servicios conexos', sector: M },
  { codigo: '71102', descripcion: 'Servicios de ingeniería', sector: M },
  { codigo: '71103', descripcion: 'Servicios de agrimensura, topografía, cartografía, prospección y geofísica y servicios conexos', sector: M },
  { codigo: '71200', descripcion: 'Ensayos y análisis técnicos', sector: M },
  { codigo: '72100', descripcion: 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería', sector: M },
  { codigo: '72199', descripcion: 'Investigaciones científicas', sector: M },
  { codigo: '72200', descripcion: 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades científica y desarrollo', sector: M },
  { codigo: '73100', descripcion: 'Publicidad', sector: M },
  { codigo: '73200', descripcion: 'Investigación de mercados y realización de encuestas de opinión pública', sector: M },
  { codigo: '74100', descripcion: 'Actividades de diseño especializado', sector: M },
  { codigo: '74200', descripcion: 'Actividades de fotografía', sector: M },
  { codigo: '74900', descripcion: 'Servicios profesionales y científicos ncp', sector: M },
  { codigo: '75000', descripcion: 'Actividades veterinarias', sector: M },

  // ── N · Actividades de servicios administrativos y de apoyo ───────────────
  { codigo: '77101', descripcion: 'Alquiler de equipo de transporte terrestre', sector: N },
  { codigo: '77102', descripcion: 'Alquiler de equipo de transporte acuático', sector: N },
  { codigo: '77103', descripcion: 'Alquiler de equipo de transporte por vía aérea', sector: N },
  { codigo: '77210', descripcion: 'Alquiler y arrendamiento de equipo de recreo y deportivo', sector: N },
  { codigo: '77220', descripcion: 'Alquiler de cintas de video y discos', sector: N },
  { codigo: '77290', descripcion: 'Alquiler de otros efectos personales y enseres domésticos', sector: N },
  { codigo: '77300', descripcion: 'Alquiler de maquinaria y equipo', sector: N },
  { codigo: '77400', descripcion: 'Arrendamiento de productos de propiedad intelectual', sector: N },
  { codigo: '78100', descripcion: 'Obtención y dotación de personal', sector: N },
  { codigo: '78200', descripcion: 'Actividades de las agencias de trabajo temporal', sector: N },
  { codigo: '78300', descripcion: 'Dotación de recursos humanos y gestión; gestión de las funciones de recursos humanos', sector: N },
  { codigo: '79110', descripcion: 'Actividades de agencias de viajes y organizadores de viajes; actividades de asistencia a turistas', sector: N },
  { codigo: '79120', descripcion: 'Actividades de los operadores turísticos', sector: N },
  { codigo: '79900', descripcion: 'Otros servicios de reservas y actividades relacionadas', sector: N },
  { codigo: '80100', descripcion: 'Servicios de seguridad privados', sector: N },
  { codigo: '80201', descripcion: 'Actividades de servicios de sistemas de seguridad', sector: N },
  { codigo: '80202', descripcion: 'Actividades para la prestación de sistemas de seguridad', sector: N },
  { codigo: '80300', descripcion: 'Actividades de investigación', sector: N },
  { codigo: '81100', descripcion: 'Actividades combinadas de mantenimiento de edificios e instalaciones', sector: N },
  { codigo: '81210', descripcion: 'Limpieza general de edificios', sector: N },
  { codigo: '81290', descripcion: 'Otras actividades combinadas de mantenimiento de edificios e instalaciones ncp', sector: N },
  { codigo: '81300', descripcion: 'Servicio de jardinería', sector: N },
  { codigo: '82110', descripcion: 'Servicios administrativos de oficinas', sector: N },
  { codigo: '82190', descripcion: 'Servicio de fotocopiado y similares, excepto en imprentas', sector: N },
  { codigo: '82200', descripcion: 'Actividades de las centrales de llamadas (call center)', sector: N },
  { codigo: '82300', descripcion: 'Organización de convenciones y ferias de negocios', sector: N },
  { codigo: '82910', descripcion: 'Actividades de agencias de cobro y oficinas de crédito', sector: N },
  { codigo: '82921', descripcion: 'Servicios de envase y empaque de productos alimenticios', sector: N },
  { codigo: '82922', descripcion: 'Servicios de envase y empaque de productos medicinales', sector: N },
  { codigo: '82929', descripcion: 'Servicio de envase y empaque ncp', sector: N },
  { codigo: '82990', descripcion: 'Actividades de apoyo empresariales ncp', sector: N },

  // ── O · Administración pública y defensa ──────────────────────────────────
  { codigo: '84110', descripcion: 'Actividades de la Administración Pública en general', sector: O },
  { codigo: '84111', descripcion: 'Alcaldías municipales', sector: O },
  { codigo: '84120', descripcion: 'Regulación de las actividades de prestación de servicios sanitarios, educativos, culturales y otros servicios sociales, excepto seguridad social', sector: O },
  { codigo: '84130', descripcion: 'Regulación y facilitación de la actividad económica', sector: O },
  { codigo: '84210', descripcion: 'Actividades de administración y funcionamiento del Ministerio de Relaciones Exteriores', sector: O },
  { codigo: '84220', descripcion: 'Actividades de defensa', sector: O },
  { codigo: '84230', descripcion: 'Actividades de mantenimiento del orden público y de seguridad', sector: O },
  { codigo: '84300', descripcion: 'Actividades de planes de seguridad social de afiliación obligatoria', sector: O },

  // ── P · Enseñanza ─────────────────────────────────────────────────────────
  { codigo: '85101', descripcion: 'Guardería educativa', sector: P },
  { codigo: '85102', descripcion: 'Enseñanza preescolar o parvularia', sector: P },
  { codigo: '85103', descripcion: 'Enseñanza primaria', sector: P },
  { codigo: '85104', descripcion: 'Servicio de educación preescolar y primaria integrada', sector: P },
  { codigo: '85211', descripcion: 'Enseñanza secundaria tercer ciclo (7°, 8° y 9°)', sector: P },
  { codigo: '85212', descripcion: 'Enseñanza secundaria de formación general bachillerato', sector: P },
  { codigo: '85221', descripcion: 'Enseñanza secundaria de formación técnica y profesional', sector: P },
  { codigo: '85222', descripcion: 'Enseñanza secundaria de formación técnica y profesional integrada con enseñanza primaria', sector: P },
  { codigo: '85301', descripcion: 'Enseñanza superior universitaria', sector: P },
  { codigo: '85302', descripcion: 'Enseñanza superior no universitaria', sector: P },
  { codigo: '85303', descripcion: 'Enseñanza superior integrada a educación secundaria y/o primaria', sector: P },
  { codigo: '85410', descripcion: 'Educación deportiva y recreativa', sector: P },
  { codigo: '85420', descripcion: 'Educación cultural', sector: P },
  { codigo: '85490', descripcion: 'Otros tipos de enseñanza n.c.p.', sector: P },
  { codigo: '85499', descripcion: 'Enseñanza formal', sector: P },
  { codigo: '85500', descripcion: 'Servicios de apoyo a la enseñanza', sector: P },

  // ── Q · Actividades de atención de la salud humana ───────────────────────
  { codigo: '86100', descripcion: 'Actividades de hospitales', sector: Q },
  { codigo: '86201', descripcion: 'Clínicas médicas', sector: Q },
  { codigo: '86202', descripcion: 'Servicios de Odontología', sector: Q },
  { codigo: '86203', descripcion: 'Servicios médicos', sector: Q },
  { codigo: '86901', descripcion: 'Servicios de análisis y estudios de diagnóstico', sector: Q },
  { codigo: '86902', descripcion: 'Actividades de atención de la salud humana', sector: Q },
  { codigo: '86909', descripcion: 'Otros Servicio relacionados con la salud ncp', sector: Q },
  { codigo: '87100', descripcion: 'Residencias de ancianos con atención de enfermería', sector: Q },
  { codigo: '87200', descripcion: 'Instituciones dedicadas al tratamiento del retraso mental, problemas de salud mental y el uso indebido de sustancias nocivas', sector: Q },
  { codigo: '87300', descripcion: 'Instituciones dedicadas al cuidado de ancianos y discapacitados', sector: Q },
  { codigo: '87900', descripcion: 'Actividades de asistencia a niños y jóvenes', sector: Q },
  { codigo: '87901', descripcion: 'Otras actividades de atención en instituciones', sector: Q },
  { codigo: '88100', descripcion: 'Actividades de asistencia sociales sin alojamiento para ancianos y discapacitados', sector: Q },
  { codigo: '88900', descripcion: 'Servicios sociales sin alojamiento ncp', sector: Q },

  // ── R · Artes, entretenimiento y recreación ───────────────────────────────
  { codigo: '90000', descripcion: 'Actividades creativas artísticas y de esparcimiento', sector: R },
  { codigo: '91010', descripcion: 'Actividades de bibliotecas y archivos', sector: R },
  { codigo: '91020', descripcion: 'Actividades de museos y preservación de lugares y edificios históricos', sector: R },
  { codigo: '91030', descripcion: 'Actividades de jardines botánicos, zoológicos y de reservas naturales', sector: R },
  { codigo: '92000', descripcion: 'Actividades de juegos y apuestas', sector: R },
  { codigo: '93110', descripcion: 'Gestión de instalaciones deportivas', sector: R },
  { codigo: '93120', descripcion: 'Actividades de clubes deportivos', sector: R },
  { codigo: '93190', descripcion: 'Otras actividades deportivas', sector: R },
  { codigo: '93210', descripcion: 'Actividades de parques de atracciones y parques temáticos', sector: R },
  { codigo: '93291', descripcion: 'Discotecas y salas de baile', sector: R },
  { codigo: '93298', descripcion: 'Centros vacacionales', sector: R },
  { codigo: '93299', descripcion: 'Actividades de esparcimiento ncp', sector: R },

  // ── S · Otras actividades de servicios ────────────────────────────────────
  { codigo: '94110', descripcion: 'Actividades de organizaciones empresariales y de empleadores', sector: S },
  { codigo: '94120', descripcion: 'Actividades de organizaciones profesionales', sector: S },
  { codigo: '94200', descripcion: 'Actividades de sindicatos', sector: S },
  { codigo: '94910', descripcion: 'Actividades de organizaciones religiosas', sector: S },
  { codigo: '94920', descripcion: 'Actividades de organizaciones políticas', sector: S },
  { codigo: '94990', descripcion: 'Actividades de asociaciones n.c.p.', sector: S },
  { codigo: '95110', descripcion: 'Reparación de computadoras y equipo periférico', sector: S },
  { codigo: '95120', descripcion: 'Reparación de equipo de comunicación', sector: S },
  { codigo: '95210', descripcion: 'Reparación de aparatos electrónicos de consumo', sector: S },
  { codigo: '95220', descripcion: 'Reparación de aparatos doméstico y equipo de hogar y jardín', sector: S },
  { codigo: '95230', descripcion: 'Reparación de calzado y artículos de cuero', sector: S },
  { codigo: '95240', descripcion: 'Reparación de muebles y accesorios para el hogar', sector: S },
  { codigo: '95291', descripcion: 'Reparación de Instrumentos musicales', sector: S },
  { codigo: '95292', descripcion: 'Servicios de cerrajería y copiado de llaves', sector: S },
  { codigo: '95293', descripcion: 'Reparación de joyas y relojes', sector: S },
  { codigo: '95294', descripcion: 'Reparación de bicicletas, sillas de ruedas y rodados n.c.p.', sector: S },
  { codigo: '95299', descripcion: 'Reparaciones de enseres personales n.c.p.', sector: S },
  { codigo: '96010', descripcion: 'Lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco', sector: S },
  { codigo: '96020', descripcion: 'Peluquería y otros tratamientos de belleza', sector: S },
  { codigo: '96030', descripcion: 'Pompas fúnebres y actividades conexas', sector: S },
  { codigo: '96091', descripcion: 'Servicios de sauna y otros servicios para la estética corporal n.c.p.', sector: S },
  { codigo: '96092', descripcion: 'Servicios n.c.p.', sector: S },

  // ── T · Actividades de los hogares como empleadores ───────────────────────
  { codigo: '97000', descripcion: 'Actividad de los hogares en calidad de empleadores de personal doméstico', sector: T },
  { codigo: '98100', descripcion: 'Actividades indiferenciadas de producción de bienes de los hogares privados para uso propio', sector: T },
  { codigo: '98200', descripcion: 'Actividades indiferenciadas de producción de servicios de los hogares privados para uso propio', sector: T },

  // ── U · Actividades de organizaciones extraterritoriales ──────────────────
  { codigo: '99000', descripcion: 'Actividades de organizaciones y órganos extraterritoriales', sector: U },

  // ── Z · Empleados y otras personas naturales ──────────────────────────────
  { codigo: '10001', descripcion: 'Empleados', sector: Z },
  { codigo: '10002', descripcion: 'Jubilado', sector: Z },
  { codigo: '10003', descripcion: 'Estudiante', sector: Z },
  { codigo: '10004', descripcion: 'Desempleado', sector: Z },
  { codigo: '10005', descripcion: 'Otros', sector: Z },
];

// Lookup rápido: código → actividad
const _byCode = new Map(ACTIVIDADES_ECONOMICAS_SV.map((a) => [a.codigo, a]));
export function getActividadByCodigo(codigo: string): ActividadEconomica | undefined {
  return _byCode.get(codigo);
}
