// CAT-028 Régimen (MH). El `value` es el código que FacturaLlama espera en
// regime del payload FEX. Debe coincidir con server/src/lib/cat028.ts.
export type Regimen = { value: string; label: string }

export const CAT028: Regimen[] = [
  { value: '1000.000', label: 'Exportación Definitiva, Régimen Común' },
  { value: '1040.000', label: 'Exportación Definitiva Sustitución de Mercancías, Régimen Común' },
  { value: '1041.020', label: 'Exportación Definitiva Proveniente de Franquicia Provisional, Franq. Presidenciales exento de DAI' },
  { value: '1041.021', label: 'Exportación Definitiva Proveniente de Franquicia Provisional, Franq. Presidenciales exento de DAI e IVA' },
  { value: '1048.025', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Maquinaria y Equipo LZF. DPA' },
  { value: '1048.031', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Distribución Internacional' },
  { value: '1048.032', label: 'Exportación Definitiva Proveniente. de Franquicia Definitiva, Operaciones Internacionales de Logística' },
  { value: '1048.033', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Centro Internacional de llamadas(Call Center)' },
  { value: '1048.034', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Tecnologias de Información LSI' },
  { value: '1048.035', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Investigación y Desarrollo LSI' },
  { value: '1048.036', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Reparación y Mantenimiento de Embarcaciones Marítimas LSI' },
  { value: '1048.037', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Reparación y Mantenimiento de Aeronaves LSI' },
  { value: '1048.038', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Procesos Empresariales LSI' },
  { value: '1048.039', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Servicios Medico-Hospitalarios LSI' },
  { value: '1048.040', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Servicios Financieros Internacionales LSI' },
  { value: '1048.043', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Reparación y Mantenimiento de Contenedores LSI' },
  { value: '1048.044', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Reparación de Equipos Tecnológicos LSI' },
  { value: '1048.054', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Atención Ancianos y Convalecientes LSI' },
  { value: '1048.055', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Telemedicina LSI' },
  { value: '1048.056', label: 'Exportación Definitiva Proveniente de Franquicia Definitiva, Cinematografía LSI' },
  { value: '1052.000', label: 'Exportación Definitiva de DPA con origen en Compras Locales, Régimen Común' },
  { value: '1054.000', label: 'Exportación Definitiva de Zona Franca con origen en Compras Locales, Régimen Común' },
  { value: '1100.000', label: 'Exportación Definitiva de Envíos de Socorro , Régimen Común' },
  { value: '1200.000', label: 'Exportación Definitiva de Envíos Postales, Régimen Común' },
  { value: '1300.000', label: 'Exportación Definitiva Envíos que  requieren despacho urgente, Régimen Común' },
  { value: '1400.000', label: 'Exportación Definitiva  Courier, Régimen Común' },
  { value: '1400.011', label: 'Exportación Definitiva  Courier, Muestras Sin Valor Comercial' },
  { value: '1400.012', label: 'Exportación Definitiva  Courier, Material Publicitario' },
  { value: '1400.017', label: 'Exportación Definitiva  Courier, Declaración de Documentos' },
  { value: '1500.000', label: 'Exportación Definitiva Menaje de casa, Régimen Común' },
  { value: '2100.000', label: 'Exportación Temporal para Perfeccionamiento Pasivo, Régimen Común' },
  { value: '2100.065', label: 'Exportación Temporal para Perfeccionamiento Pasivo, De Mercado Nacional a ZF o DPA' },
  { value: '2200.000', label: 'Exportación Temporal con Reimportación en el mismo estado, Régimen Común' },
  { value: '2200.065', label: 'Exportación Temporal con Reimportación en el mismo estado, De Mercado Nacional a ZF o DPA' },
  { value: '2400.000', label: 'Traslados Definitivos' },
  { value: '3050.000', label: 'Reexportación Proveniente de Importación Temporal, Régimen Común' },
  { value: '3051.000', label: 'Reexportación Proveniente de Tiendas Libres, Régimen Común' },
  { value: '3052.000', label: 'Reexportación Proveniente de Admisión Temporal para Perfeccionamiento Activo, Régimen Común' },
  { value: '3053.000', label: 'Reexportación Proveniente de Admisión Temporal, Régimen Común' },
  { value: '3054.000', label: 'Reexportación Proveniente de Régimen de Zona Franca, Régimen Común' },
  { value: '3055.000', label: 'Reexportación Proveniente de Admisión Temporal para Perfeccionamiento Activo con Garantía, Régimen Común' },
  { value: '3056.000', label: 'Reexportación Proveniente de Admisión Temporal Distribución Internacional Parque de Servicios, Régimen Común' },
  { value: '3056.047', label: 'Reexportación Proveniente de Admisión Temporal Distribución Internacional Parque de Servicios, Remisión a Departamento de Subastas' },
  { value: '3056.057', label: 'Reexportación Proveniente de Admisión Temporal Distribución Internacional Parque de Servicios, Remisión entre Usuarios Directos del Mismo Parque de Servicios' },
  { value: '3056.058', label: 'Reexportación Proveniente de Admisión Temporal Distribución Internacional Parque de Servicios, Remisión entre Usuarios Directos de Diferente Parque de Servicios' },
  { value: '3056.072', label: 'Reexportación Proveniente de Admisión Temporal Distribución Internacional Parque de Servicios, Decreto 738 Eléctricos e Híbridos' },
  { value: '3056.081', label: 'Reexportación Proveniente de Admisión Temporal Distribución Internacional Parque de Servicios, Remisión entre Usuarios Directos LSI' },
  { value: '3056.084', label: 'Reexportación Proveniente de Admisión Temporal Distribución Internacional Parque de Servicios, De una LSI para un DPA' },
  { value: '3056.085', label: 'Reexportación Proveniente de Admisión Temporal Distribución Internacional Parque de Servicios, De una LSI para una ZF' },
  { value: '3057.000', label: 'Reexportación Proveniente de Admisión Temporal Operaciones Internacional de Logística Parque de Servicios, Régimen Común' },
  { value: '3057.047', label: 'Reexportación Proveniente de Admisión Temporal Operaciones Internacional de Logística Parque de Servicios, Remisión a Departamento de Subastas' },
  { value: '3057.057', label: 'Reexportación Proveniente de Admisión Temporal Operaciones Internacional de Logística Parque de Servicios, Remisión entre Usuarios Directos del Mismo Parque de Servicios' },
  { value: '3057.058', label: 'Reexportación Proveniente de Admisión Temporal Operaciones Internacional de Logística Parque de Servicios, Remisión entre Usuarios Directos de Diferente Parque de Servicios' },
  { value: '3057.081', label: 'Reexportación Proveniente de Admisión Temporal Operaciones Internacional de Logística Parque de Servicios, Remisión entre Usuarios Directos LSI' },
  { value: '3057.084', label: 'Reexportación Proveniente de Admisión Temporal Operaciones Internacional de Logística Parque de Servicios, De una LSI para un DPA' },
  { value: '3057.085', label: 'Reexportación Proveniente de Admisión Temporal Operaciones Internacional de Logística Parque de Servicios, De una LSI para una ZF' },
  { value: '3058.033', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Centro Internacional de llamadas(Call Center)' },
  { value: '3058.034', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Tecnologías de Información LSI' },
  { value: '3058.035', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Investigación y Desarrollo LSI' },
  { value: '3058.036', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Reparación y Mantenimiento de Embarcaciones Marítimas LSI' },
  { value: '3058.037', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Reparación y Mantenimiento de Aeronaves LSI' },
  { value: '3058.038', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Procesos Empresariales LSI' },
  { value: '3058.039', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Servicios Medico-Hospitalarios LSI' },
  { value: '3058.040', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Servicios Financieros Internacionales LSI' },
  { value: '3058.043', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Reparación y Mantenimiento de Contenedores LSI' },
  { value: '3058.044', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Reparación de Equipos Tecnológicos LSI' },
  { value: '3058.054', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Atención Ancianos y Convalecientes LSI' },
  { value: '3058.055', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Telemedicina LSI' },
  { value: '3058.056', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Cinematografía LSI' },
  { value: '3058.082', label: 'Reexportación Proveniente de Admisión Temporal Centro Servicio LSI, Remisión entre Centros de Servicios LSI' },
  { value: '3059.000', label: 'Reexportación Proveniente de Admisión Temporal Reparación de Equipo Tecnológico Parque de Servicios, Régimen Común' },
  { value: '3059.057', label: 'Reexportación Proveniente de Admisión Temporal Reparación de Equipo Tecnológico Parque de Servicios, Remisión entre Usuarios Directos del Mismo Parque de Servicios' },
  { value: '3059.058', label: 'Reexportación Proveniente de Admisión Temporal Reparación de Equipo Tecnológico Parque de Servicios, Remisión entre Usuarios Directos de Diferente Parque de Servicios' },
  { value: '3059.033', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Centro Internacional de llamadas(Call Center)' },
  { value: '3059.034', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Tecnologías de Información LSI' },
  { value: '3059.035', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Investigación y Desarrollo LSI' },
  { value: '3059.038', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Procesos Empresariales LSI' },
  { value: '3059.039', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Servicios Medico-Hospitalarios LSI' },
  { value: '3059.040', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Servicios Financieros Internacionales LSI' },
  { value: '3059.044', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Reparación de Equipos Tecnológicos LSI' },
  { value: '3059.047', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Remisión a Departamento de Subastas' },
  { value: '3059.054', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Atención Ancianos y Convalecientes LSI' },
  { value: '3059.055', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Telemedicina LS' },
  { value: '3059.056', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Cinematografía LSI' },
  { value: '3059.081', label: 'Reexportación Proveniente de Servicios Internacionales en Parques de Servicios, Remisión entre Usuarios Directos' },
  { value: '3070.000', label: 'Reexportación Proveniente de Depósito., Régimen Común' },
  { value: '3070.047', label: 'Reexportación Proveniente de Depósito., Remisión a Departamento de Subastas' },
  { value: '3070.072', label: 'Reexportación Proveniente de Depósito., Decreto 738 Eléctricos e Híbridos' },
  { value: '3071.000', label: 'Reexp. Prov. de Deposito.' },
  { value: '0000.000', label: 'Tránsito Aduanero' },
]

export const CAT028_CODIGOS: ReadonlySet<string> = new Set(CAT028.map((r) => r.value))

export function resolverRegimen(code?: string | null): string {
  if (!code) return ''
  return CAT028.find((r) => r.value === code)?.label ?? code
}
