// CAT-019 — Clasificación de Actividades Económicas del Ministerio de Hacienda de El Salvador
// Basado en CIIU Rev. 4 adaptado para el sistema de facturación electrónica (DTE).

export type ActividadEconomica = {
  codigo: string;
  descripcion: string;
  sector: string;
};

// Los sectores deben coincidir exactamente con los valores de SECTORES_CAT019 más abajo.
export const SECTORES_CAT019 = [
  'Agricultura, ganadería y pesca',
  'Minería y canteras',
  'Manufactura',
  'Electricidad y gas',
  'Agua y saneamiento',
  'Construcción',
  'Comercio',
  'Transporte y almacenamiento',
  'Alojamiento y restaurantes',
  'Información y comunicaciones',
  'Servicios financieros',
  'Bienes raíces',
  'Servicios profesionales y técnicos',
  'Servicios administrativos',
  'Administración pública',
  'Educación',
  'Salud',
  'Cultura y entretenimiento',
  'Otros servicios',
  'Hogares como empleadores',
  'Organizaciones extraterritoriales',
  'Empleados y personas naturales',
] as const;

export type SectorCAT019 = typeof SECTORES_CAT019[number];

const A = 'Agricultura, ganadería y pesca';
const B = 'Minería y canteras';
const C = 'Manufactura';
const D = 'Electricidad y gas';
const E = 'Agua y saneamiento';
const F = 'Construcción';
const G = 'Comercio';
const H = 'Transporte y almacenamiento';
const I = 'Alojamiento y restaurantes';
const J = 'Información y comunicaciones';
const K = 'Servicios financieros';
const L = 'Bienes raíces';
const M = 'Servicios profesionales y técnicos';
const N = 'Servicios administrativos';
const O = 'Administración pública';
const P = 'Educación';
const Q = 'Salud';
const R = 'Cultura y entretenimiento';
const S = 'Otros servicios';
const T = 'Hogares como empleadores';
const U = 'Organizaciones extraterritoriales';
const Z = 'Empleados y personas naturales';

export const ACTIVIDADES_ECONOMICAS_SV: ActividadEconomica[] = [
  // ── A · Agricultura, ganadería, silvicultura y pesca ──────────────────────
  { codigo: '01111', descripcion: 'Cultivo de cereales (excepto arroz)', sector: A },
  { codigo: '01112', descripcion: 'Cultivo de leguminosas', sector: A },
  { codigo: '01113', descripcion: 'Cultivo de oleaginosas', sector: A },
  { codigo: '01114', descripcion: 'Cultivo de plantas para semillas', sector: A },
  { codigo: '01119', descripcion: 'Otros cultivos de cereales n.c.p.', sector: A },
  { codigo: '01120', descripcion: 'Cultivo de arroz', sector: A },
  { codigo: '01131', descripcion: 'Cultivo de raíces y tubérculos', sector: A },
  { codigo: '01132', descripcion: 'Cultivo de brotes y bulbos', sector: A },
  { codigo: '01133', descripcion: 'Cultivo de hortalizas de fruto', sector: A },
  { codigo: '01134', descripcion: 'Cultivo de hortalizas de hoja', sector: A },
  { codigo: '01140', descripcion: 'Cultivo de caña de azúcar', sector: A },
  { codigo: '01150', descripcion: 'Cultivo de tabaco', sector: A },
  { codigo: '01161', descripcion: 'Cultivo de algodón', sector: A },
  { codigo: '01162', descripcion: 'Cultivo de fibras vegetales', sector: A },
  { codigo: '01191', descripcion: 'Cultivo de plantas no perennes (semillas y flores)', sector: A },
  { codigo: '01192', descripcion: 'Cultivo de cereales y pastos para alimentación animal', sector: A },
  { codigo: '01199', descripcion: 'Producción de cultivos no estacionales n.c.p.', sector: A },
  { codigo: '01220', descripcion: 'Cultivo de frutas tropicales', sector: A },
  { codigo: '01230', descripcion: 'Cultivo de cítricos', sector: A },
  { codigo: '01240', descripcion: 'Cultivo de frutas de pepita y hueso', sector: A },
  { codigo: '01251', descripcion: 'Cultivo de otras frutas', sector: A },
  { codigo: '01252', descripcion: 'Cultivo de frutas de árbol y arbusto', sector: A },
  { codigo: '01260', descripcion: 'Cultivo de frutas oleaginosas', sector: A },
  { codigo: '01271', descripcion: 'Cultivo de café', sector: A },
  { codigo: '01272', descripcion: 'Cultivo de plantas para bebidas', sector: A },
  { codigo: '01281', descripcion: 'Cultivo de especias y plantas aromáticas', sector: A },
  { codigo: '01282', descripcion: 'Cultivo de plantas medicinales', sector: A },
  { codigo: '01291', descripcion: 'Cultivo de árbol de hule', sector: A },
  { codigo: '01292', descripcion: 'Cultivo de plantas químicas y tintóreas', sector: A },
  { codigo: '01299', descripcion: 'Producción de cultivos perennes n.c.p.', sector: A },
  { codigo: '01300', descripcion: 'Propagación de plantas', sector: A },
  { codigo: '01301', descripcion: 'Cultivo de plantas ornamentales', sector: A },
  { codigo: '01410', descripcion: 'Cría de ganado bovino', sector: A },
  { codigo: '01420', descripcion: 'Cría de caballos y otros équidos', sector: A },
  { codigo: '01440', descripcion: 'Cría de ovejas y cabras', sector: A },
  { codigo: '01450', descripcion: 'Cría de cerdos', sector: A },
  { codigo: '01460', descripcion: 'Cría de aves de corral', sector: A },
  { codigo: '01491', descripcion: 'Apicultura', sector: A },
  { codigo: '01492', descripcion: 'Cría de conejos', sector: A },
  { codigo: '01493', descripcion: 'Cría de iguanas', sector: A },
  { codigo: '01494', descripcion: 'Cría de mariposas', sector: A },
  { codigo: '01499', descripcion: 'Producción de otros productos de origen animal n.c.p.', sector: A },
  { codigo: '01500', descripcion: 'Cultivo de productos agrícolas en combinación con la cría de animales', sector: A },
  { codigo: '01611', descripcion: 'Servicios de maquinaria agrícola', sector: A },
  { codigo: '01612', descripcion: 'Control de plagas', sector: A },
  { codigo: '01613', descripcion: 'Servicios de riego', sector: A },
  { codigo: '01614', descripcion: 'Contratación de mano de obra agrícola', sector: A },
  { codigo: '01619', descripcion: 'Servicios agrícolas n.c.p.', sector: A },
  { codigo: '01621', descripcion: 'Servicios de mejora de la reproducción animal', sector: A },
  { codigo: '01622', descripcion: 'Servicios de mano de obra pecuaria', sector: A },
  { codigo: '01629', descripcion: 'Servicios pecuarios n.c.p.', sector: A },
  { codigo: '01631', descripcion: 'Preparación postcosecha de cultivos', sector: A },
  { codigo: '01632', descripcion: 'Servicios de procesamiento de café', sector: A },
  { codigo: '01633', descripcion: 'Procesamiento de plantas textiles', sector: A },
  { codigo: '01640', descripcion: 'Tratamiento de semillas para propagación', sector: A },
  { codigo: '01700', descripcion: 'Caza ordinaria y mediante trampas y actividades de servicios conexas', sector: A },
  { codigo: '02100', descripcion: 'Silvicultura y otras actividades forestales', sector: A },
  { codigo: '02200', descripcion: 'Extracción de madera', sector: A },
  { codigo: '02300', descripcion: 'Recolección de productos forestales distintos de la madera', sector: A },
  { codigo: '02400', descripcion: 'Servicios de apoyo a la silvicultura', sector: A },
  { codigo: '03110', descripcion: 'Pesca marítima', sector: A },
  { codigo: '03120', descripcion: 'Pesca de agua dulce', sector: A },
  { codigo: '03210', descripcion: 'Acuicultura marítima', sector: A },
  { codigo: '03220', descripcion: 'Acuicultura de agua dulce', sector: A },
  { codigo: '03300', descripcion: 'Servicios de apoyo a la pesca y la acuicultura', sector: A },

  // ── B · Explotación de minas y canteras ───────────────────────────────────
  { codigo: '05100', descripcion: 'Extracción de hulla (carbón de piedra)', sector: B },
  { codigo: '05200', descripcion: 'Extracción de lignito', sector: B },
  { codigo: '06100', descripcion: 'Extracción de petróleo crudo', sector: B },
  { codigo: '06200', descripcion: 'Extracción de gas natural', sector: B },
  { codigo: '07100', descripcion: 'Extracción de minerales de hierro', sector: B },
  { codigo: '07210', descripcion: 'Extracción de uranio y torio', sector: B },
  { codigo: '07290', descripcion: 'Extracción de otros minerales metalíferos no ferrosos', sector: B },
  { codigo: '08100', descripcion: 'Extracción de piedra, arena y arcilla', sector: B },
  { codigo: '08910', descripcion: 'Extracción de minerales para la fabricación de abonos y productos químicos', sector: B },
  { codigo: '08920', descripcion: 'Extracción de turba', sector: B },
  { codigo: '08930', descripcion: 'Extracción de sal', sector: B },
  { codigo: '08990', descripcion: 'Explotación de otras minas y canteras n.c.p.', sector: B },
  { codigo: '09100', descripcion: 'Actividades de apoyo para la extracción de petróleo y gas natural', sector: B },
  { codigo: '09900', descripcion: 'Actividades de apoyo para la explotación de otras minas y canteras', sector: B },

  // ── C · Industrias manufactureras ─────────────────────────────────────────
  { codigo: '10101', descripcion: 'Servicios de matadero', sector: C },
  { codigo: '10102', descripcion: 'Matanza de ganado bovino y porcino', sector: C },
  { codigo: '10103', descripcion: 'Matanza de aves de corral', sector: C },
  { codigo: '10104', descripcion: 'Elaboración de embutidos y tripas naturales', sector: C },
  { codigo: '10105', descripcion: 'Conservación y envasado de carnes', sector: C },
  { codigo: '10106', descripcion: 'Producción de grasas y aceites animales', sector: C },
  { codigo: '10107', descripcion: 'Servicios de molienda de carne', sector: C },
  { codigo: '10108', descripcion: 'Elaboración de productos cárnicos n.c.p.', sector: C },
  { codigo: '10201', descripcion: 'Elaboración y conservación de pescado, crustáceos y moluscos', sector: C },
  { codigo: '10209', descripcion: 'Elaboración de productos de pescado n.c.p.', sector: C },
  { codigo: '10301', descripcion: 'Elaboración de jugos de frutas y hortalizas', sector: C },
  { codigo: '10302', descripcion: 'Elaboración de mermeladas, jaleas y frutas secas', sector: C },
  { codigo: '10309', descripcion: 'Elaboración de otros productos de frutas y hortalizas n.c.p.', sector: C },
  { codigo: '10401', descripcion: 'Elaboración de aceites y grasas vegetales y animales comestibles', sector: C },
  { codigo: '10402', descripcion: 'Elaboración de aceites y grasas no comestibles', sector: C },
  { codigo: '10409', descripcion: 'Servicios de aceite maquilado', sector: C },
  { codigo: '10501', descripcion: 'Elaboración de productos lácteos', sector: C },
  { codigo: '10502', descripcion: 'Elaboración de sorbetes y helados', sector: C },
  { codigo: '10503', descripcion: 'Elaboración de quesos', sector: C },
  { codigo: '10611', descripcion: 'Molienda de granos', sector: C },
  { codigo: '10612', descripcion: 'Elaboración de cereales para el desayuno', sector: C },
  { codigo: '10613', descripcion: 'Servicios de procesamiento de productos agrícolas n.c.p.', sector: C },
  { codigo: '10621', descripcion: 'Elaboración de almidones y productos derivados del almidón', sector: C },
  { codigo: '10628', descripcion: 'Servicios de molienda de maíz', sector: C },
  { codigo: '10711', descripcion: 'Elaboración de tortillas', sector: C },
  { codigo: '10712', descripcion: 'Elaboración de pan, galletas y barquillos', sector: C },
  { codigo: '10713', descripcion: 'Elaboración de productos de panadería n.c.p.', sector: C },
  { codigo: '10721', descripcion: 'Ingenios azucareros', sector: C },
  { codigo: '10722', descripcion: 'Molienda de caña de azúcar para producción de dulces', sector: C },
  { codigo: '10723', descripcion: 'Producción de melaza de caña de azúcar', sector: C },
  { codigo: '10724', descripcion: 'Maquila de caña de azúcar', sector: C },
  { codigo: '10730', descripcion: 'Elaboración de cacao, chocolate y productos de confitería', sector: C },
  { codigo: '10740', descripcion: 'Elaboración de pasta y fideos', sector: C },
  { codigo: '10750', descripcion: 'Elaboración de comidas y platos preparados', sector: C },
  { codigo: '10791', descripcion: 'Elaboración de productos a base de café', sector: C },
  { codigo: '10792', descripcion: 'Elaboración de condimentos y especias', sector: C },
  { codigo: '10793', descripcion: 'Elaboración de sopas y consomés', sector: C },
  { codigo: '10794', descripcion: 'Elaboración de bocadillos tostados y fritos', sector: C },
  { codigo: '10799', descripcion: 'Elaboración de otros productos alimenticios n.c.p.', sector: C },
  { codigo: '10800', descripcion: 'Elaboración de alimentos preparados para animales', sector: C },
  { codigo: '11012', descripcion: 'Elaboración de licores y aguardientes', sector: C },
  { codigo: '11020', descripcion: 'Elaboración de vinos', sector: C },
  { codigo: '11030', descripcion: 'Elaboración de cerveza', sector: C },
  { codigo: '11041', descripcion: 'Elaboración de agua carbonatada', sector: C },
  { codigo: '11042', descripcion: 'Embotellado de agua purificada', sector: C },
  { codigo: '11043', descripcion: 'Elaboración de bebidas gaseosas', sector: C },
  { codigo: '11048', descripcion: 'Maquila de agua carbonatada', sector: C },
  { codigo: '11049', descripcion: 'Elaboración de bebidas no alcohólicas n.c.p.', sector: C },
  { codigo: '12000', descripcion: 'Elaboración de productos de tabaco', sector: C },
  { codigo: '13111', descripcion: 'Preparación e hilado de fibras textiles', sector: C },
  { codigo: '13112', descripcion: 'Fabricación de hilados', sector: C },
  { codigo: '13120', descripcion: 'Fabricación de telas', sector: C },
  { codigo: '13130', descripcion: 'Acabado de productos textiles', sector: C },
  { codigo: '13910', descripcion: 'Fabricación de tejidos de punto y ganchillo', sector: C },
  { codigo: '13921', descripcion: 'Fabricación de artículos textiles para el hogar', sector: C },
  { codigo: '13922', descripcion: 'Fabricación de sacos, bolsas y artículos textiles para envasado', sector: C },
  { codigo: '13929', descripcion: 'Fabricación de artículos textiles excepto prendas de vestir n.c.p.', sector: C },
  { codigo: '13930', descripcion: 'Fabricación de tapices y alfombras', sector: C },
  { codigo: '13941', descripcion: 'Fabricación de cuerdas de fibra natural', sector: C },
  { codigo: '13942', descripcion: 'Fabricación de redes', sector: C },
  { codigo: '13948', descripcion: 'Maquila de productos tejidos', sector: C },
  { codigo: '13991', descripcion: 'Fabricación de ribetes y etiquetas para ropa', sector: C },
  { codigo: '13992', descripcion: 'Servicios de bordado', sector: C },
  { codigo: '13999', descripcion: 'Fabricación de otros productos textiles n.c.p.', sector: C },
  { codigo: '14101', descripcion: 'Fabricación de ropa interior y de dormir', sector: C },
  { codigo: '14102', descripcion: 'Fabricación de ropa para niños', sector: C },
  { codigo: '14103', descripcion: 'Fabricación de ropa unisex', sector: C },
  { codigo: '14104', descripcion: 'Producción de prendas de vestir a medida', sector: C },
  { codigo: '14105', descripcion: 'Fabricación de ropa deportiva', sector: C },
  { codigo: '14106', descripcion: 'Fabricación de artesanías textiles', sector: C },
  { codigo: '14108', descripcion: 'Maquila de ropa', sector: C },
  { codigo: '14109', descripcion: 'Fabricación de prendas de vestir y accesorios n.c.p.', sector: C },
  { codigo: '14200', descripcion: 'Fabricación de artículos de piel', sector: C },
  { codigo: '14301', descripcion: 'Fabricación de calcetines y medias', sector: C },
  { codigo: '14302', descripcion: 'Fabricación de ropa interior de punto', sector: C },
  { codigo: '14309', descripcion: 'Fabricación de prendas de vestir de punto n.c.p.', sector: C },
  { codigo: '15110', descripcion: 'Curtido y adobo de cueros; adobo y teñido de pieles', sector: C },
  { codigo: '15121', descripcion: 'Fabricación de maletas, bolsos de mano y artículos similares', sector: C },
  { codigo: '15122', descripcion: 'Fabricación de arneses, monturas y artículos de talabartería', sector: C },
  { codigo: '15123', descripcion: 'Fabricación de artesanías en cuero natural y sintético', sector: C },
  { codigo: '15128', descripcion: 'Maquila de artículos de cuero', sector: C },
  { codigo: '15201', descripcion: 'Fabricación de calzado', sector: C },
  { codigo: '15202', descripcion: 'Fabricación de partes y accesorios para calzado', sector: C },
  { codigo: '15208', descripcion: 'Maquila de calzado', sector: C },
  { codigo: '16100', descripcion: 'Aserrado y acepilladura de madera', sector: C },
  { codigo: '16210', descripcion: 'Fabricación de madera laminada y contrachapada', sector: C },
  { codigo: '16220', descripcion: 'Fabricación de partes de carpintería para construcción', sector: C },
  { codigo: '16230', descripcion: 'Fabricación de recipientes de madera', sector: C },
  { codigo: '16292', descripcion: 'Fabricación de artesanías en madera y materiales trenzados', sector: C },
  { codigo: '16299', descripcion: 'Fabricación de productos de madera, corcho y materiales trenzados n.c.p.', sector: C },
  { codigo: '17010', descripcion: 'Fabricación de pasta de madera y papel', sector: C },
  { codigo: '17020', descripcion: 'Fabricación de cartón corrugado y envases de papel y cartón', sector: C },
  { codigo: '17091', descripcion: 'Fabricación de artículos de papel para uso personal y doméstico', sector: C },
  { codigo: '17092', descripcion: 'Fabricación de otros productos de papel n.c.p.', sector: C },
  { codigo: '18110', descripcion: 'Impresión', sector: C },
  { codigo: '18120', descripcion: 'Servicios relacionados con la impresión', sector: C },
  { codigo: '18200', descripcion: 'Reproducción de grabaciones', sector: C },
  { codigo: '19100', descripcion: 'Fabricación de productos de hornos de coque', sector: C },
  { codigo: '19201', descripcion: 'Fabricación de combustibles', sector: C },
  { codigo: '19202', descripcion: 'Fabricación de aceites y lubricantes', sector: C },
  { codigo: '20111', descripcion: 'Fabricación de materias primas para colorantes', sector: C },
  { codigo: '20112', descripcion: 'Fabricación de materias curtientes', sector: C },
  { codigo: '20113', descripcion: 'Fabricación de gases industriales', sector: C },
  { codigo: '20114', descripcion: 'Fabricación de alcohol etílico', sector: C },
  { codigo: '20119', descripcion: 'Fabricación de otras sustancias químicas básicas', sector: C },
  { codigo: '20120', descripcion: 'Fabricación de fertilizantes y plaguicidas', sector: C },
  { codigo: '20130', descripcion: 'Fabricación de plásticos y caucho sintético en formas primarias', sector: C },
  { codigo: '20210', descripcion: 'Fabricación de plaguicidas y otros agroquímicos', sector: C },
  { codigo: '20220', descripcion: 'Fabricación de pinturas, barnices y revestimientos similares', sector: C },
  { codigo: '20231', descripcion: 'Fabricación de jabones y detergentes', sector: C },
  { codigo: '20232', descripcion: 'Fabricación de cosméticos y artículos de tocador', sector: C },
  { codigo: '20291', descripcion: 'Fabricación de tintas de escribir y de imprimir', sector: C },
  { codigo: '20292', descripcion: 'Fabricación de artículos pirotécnicos y explosivos', sector: C },
  { codigo: '20299', descripcion: 'Fabricación de otros productos químicos n.c.p.', sector: C },
  { codigo: '20300', descripcion: 'Fabricación de fibras artificiales y sintéticas', sector: C },
  { codigo: '21001', descripcion: 'Fabricación de productos farmacéuticos y botánicos medicinales', sector: C },
  { codigo: '21008', descripcion: 'Maquila de medicamentos', sector: C },
  { codigo: '22110', descripcion: 'Fabricación de neumáticos y cámaras de caucho', sector: C },
  { codigo: '22190', descripcion: 'Fabricación de otros productos de caucho', sector: C },
  { codigo: '22201', descripcion: 'Fabricación de envases de plástico', sector: C },
  { codigo: '22202', descripcion: 'Fabricación de artículos plásticos para uso personal y doméstico', sector: C },
  { codigo: '22208', descripcion: 'Maquila de plásticos', sector: C },
  { codigo: '22209', descripcion: 'Fabricación de productos de plástico n.c.p.', sector: C },
  { codigo: '23101', descripcion: 'Fabricación de vidrio plano', sector: C },
  { codigo: '23102', descripcion: 'Fabricación de envases de vidrio', sector: C },
  { codigo: '23108', descripcion: 'Servicios de maquila de vidrio', sector: C },
  { codigo: '23109', descripcion: 'Fabricación de otros productos de vidrio n.c.p.', sector: C },
  { codigo: '23910', descripcion: 'Fabricación de productos refractarios', sector: C },
  { codigo: '23920', descripcion: 'Fabricación de materiales de construcción de arcilla', sector: C },
  { codigo: '23931', descripcion: 'Fabricación de porcelana y cerámica no refractaria', sector: C },
  { codigo: '23932', descripcion: 'Fabricación de productos de cerámica y porcelana n.c.p.', sector: C },
  { codigo: '23940', descripcion: 'Fabricación de cemento, cal y yeso', sector: C },
  { codigo: '23950', descripcion: 'Fabricación de artículos de hormigón, cemento y yeso', sector: C },
  { codigo: '23960', descripcion: 'Corte, talla y acabado de la piedra', sector: C },
  { codigo: '23990', descripcion: 'Fabricación de otros productos minerales no metálicos n.c.p.', sector: C },
  { codigo: '24100', descripcion: 'Industrias básicas de hierro y acero', sector: C },
  { codigo: '24200', descripcion: 'Fabricación de productos primarios de metales preciosos y no ferrosos', sector: C },
  { codigo: '24310', descripcion: 'Fundición de hierro y acero', sector: C },
  { codigo: '24320', descripcion: 'Fundición de metales no ferrosos', sector: C },
  { codigo: '25111', descripcion: 'Fabricación de productos metálicos estructurales', sector: C },
  { codigo: '25118', descripcion: 'Maquila de estructuras metálicas', sector: C },
  { codigo: '25120', descripcion: 'Fabricación de tanques, depósitos y recipientes de metal', sector: C },
  { codigo: '25130', descripcion: 'Fabricación de generadores de vapor', sector: C },
  { codigo: '25200', descripcion: 'Fabricación de armas y municiones', sector: C },
  { codigo: '25910', descripcion: 'Forja, prensado, estampado y laminado de metal', sector: C },
  { codigo: '25920', descripcion: 'Tratamiento y revestimiento de metales', sector: C },
  { codigo: '25930', descripcion: 'Fabricación de artículos de cuchillería, herramientas y ferretería', sector: C },
  { codigo: '25991', descripcion: 'Fabricación de envases de metal', sector: C },
  { codigo: '25992', descripcion: 'Fabricación de artículos metálicos para uso personal y doméstico', sector: C },
  { codigo: '25999', descripcion: 'Fabricación de productos metálicos elaborados n.c.p.', sector: C },
  { codigo: '26100', descripcion: 'Fabricación de componentes electrónicos', sector: C },
  { codigo: '26200', descripcion: 'Fabricación de computadoras y equipo periférico', sector: C },
  { codigo: '26300', descripcion: 'Fabricación de equipo de comunicaciones', sector: C },
  { codigo: '26400', descripcion: 'Fabricación de aparatos electrónicos de consumo', sector: C },
  { codigo: '26510', descripcion: 'Fabricación de instrumentos y aparatos de medición y control', sector: C },
  { codigo: '26520', descripcion: 'Fabricación de relojes y sus partes', sector: C },
  { codigo: '26600', descripcion: 'Fabricación de equipo de irradiación y de equipo electrónico de uso médico', sector: C },
  { codigo: '26700', descripcion: 'Fabricación de instrumentos ópticos y equipo fotográfico', sector: C },
  { codigo: '26800', descripcion: 'Fabricación de soportes magnéticos y ópticos', sector: C },
  { codigo: '27100', descripcion: 'Fabricación de motores, generadores y transformadores eléctricos', sector: C },
  { codigo: '27200', descripcion: 'Fabricación de pilas y acumuladores eléctricos', sector: C },
  { codigo: '27310', descripcion: 'Fabricación de cables de fibra óptica', sector: C },
  { codigo: '27320', descripcion: 'Fabricación de otros hilos y cables eléctricos', sector: C },
  { codigo: '27330', descripcion: 'Fabricación de dispositivos de cableado', sector: C },
  { codigo: '27400', descripcion: 'Fabricación de equipo eléctrico de iluminación', sector: C },
  { codigo: '27500', descripcion: 'Fabricación de aparatos de uso doméstico', sector: C },
  { codigo: '27900', descripcion: 'Fabricación de otro equipo eléctrico', sector: C },
  { codigo: '28110', descripcion: 'Fabricación de motores y turbinas', sector: C },
  { codigo: '28120', descripcion: 'Fabricación de equipo de propulsión fluida', sector: C },
  { codigo: '28130', descripcion: 'Fabricación de otras bombas, compresores, grifos y válvulas', sector: C },
  { codigo: '28140', descripcion: 'Fabricación de cojinetes, engranajes y órganos de transmisión', sector: C },
  { codigo: '28150', descripcion: 'Fabricación de hornos, hogueras y quemadores industriales', sector: C },
  { codigo: '28160', descripcion: 'Fabricación de equipo de elevación y manipulación', sector: C },
  { codigo: '28170', descripcion: 'Fabricación de maquinaria de oficina', sector: C },
  { codigo: '28180', descripcion: 'Fabricación de herramientas de mano motorizadas', sector: C },
  { codigo: '28190', descripcion: 'Fabricación de otra maquinaria de uso general', sector: C },
  { codigo: '28210', descripcion: 'Fabricación de maquinaria agropecuaria y forestal', sector: C },
  { codigo: '28220', descripcion: 'Fabricación de máquinas formadoras de metales y máquinas herramienta', sector: C },
  { codigo: '28230', descripcion: 'Fabricación de maquinaria metalúrgica', sector: C },
  { codigo: '28240', descripcion: 'Fabricación de maquinaria para minería, canteras y construcción', sector: C },
  { codigo: '28250', descripcion: 'Fabricación de maquinaria para elaboración de alimentos, bebidas y tabaco', sector: C },
  { codigo: '28260', descripcion: 'Fabricación de maquinaria para industria textil, confección y cuero', sector: C },
  { codigo: '28291', descripcion: 'Fabricación de maquinaria para imprenta', sector: C },
  { codigo: '28299', descripcion: 'Fabricación de maquinaria especial n.c.p.', sector: C },
  { codigo: '29100', descripcion: 'Fabricación de vehículos automotores', sector: C },
  { codigo: '29200', descripcion: 'Fabricación de carrocerías para vehículos automotores y remolques', sector: C },
  { codigo: '29300', descripcion: 'Fabricación de partes, piezas y accesorios para vehículos automotores', sector: C },
  { codigo: '30110', descripcion: 'Construcción de buques y embarcaciones', sector: C },
  { codigo: '30120', descripcion: 'Construcción y reparación de embarcaciones de recreo', sector: C },
  { codigo: '30200', descripcion: 'Fabricación de locomotoras y material rodante ferroviario', sector: C },
  { codigo: '30300', descripcion: 'Fabricación de aeronaves y naves espaciales', sector: C },
  { codigo: '30400', descripcion: 'Fabricación de vehículos militares de combate', sector: C },
  { codigo: '30910', descripcion: 'Fabricación de motocicletas', sector: C },
  { codigo: '30920', descripcion: 'Fabricación de bicicletas y sillas de ruedas', sector: C },
  { codigo: '30990', descripcion: 'Fabricación de otros equipos de transporte n.c.p.', sector: C },
  { codigo: '31001', descripcion: 'Fabricación de colchones y bases de cama', sector: C },
  { codigo: '31002', descripcion: 'Fabricación de muebles de madera a medida', sector: C },
  { codigo: '31008', descripcion: 'Maquila de muebles', sector: C },
  { codigo: '31009', descripcion: 'Fabricación de muebles n.c.p.', sector: C },
  { codigo: '32110', descripcion: 'Fabricación de joyas y artículos de metales preciosos', sector: C },
  { codigo: '32120', descripcion: 'Fabricación de bisutería y artículos similares', sector: C },
  { codigo: '32200', descripcion: 'Fabricación de instrumentos musicales', sector: C },
  { codigo: '32301', descripcion: 'Fabricación de artículos de deporte', sector: C },
  { codigo: '32308', descripcion: 'Maquila de artículos deportivos', sector: C },
  { codigo: '32401', descripcion: 'Fabricación de juegos de mesa', sector: C },
  { codigo: '32402', descripcion: 'Maquila de juguetes y juegos', sector: C },
  { codigo: '32409', descripcion: 'Fabricación de juegos y juguetes n.c.p.', sector: C },
  { codigo: '32500', descripcion: 'Fabricación de instrumentos y materiales médicos y odontológicos', sector: C },
  { codigo: '32901', descripcion: 'Fabricación de lápices, bolígrafos y artículos de papelería', sector: C },
  { codigo: '32902', descripcion: 'Fabricación de escobas, cepillos y pinceles', sector: C },
  { codigo: '32903', descripcion: 'Fabricación de artesanías en diversos materiales', sector: C },
  { codigo: '32904', descripcion: 'Fabricación de artículos personales y domésticos n.c.p.', sector: C },
  { codigo: '32905', descripcion: 'Fabricación de accesorios de costura y cuero n.c.p.', sector: C },
  { codigo: '32908', descripcion: 'Servicios de maquila n.c.p.', sector: C },
  { codigo: '32909', descripcion: 'Fabricación de productos manufacturados n.c.p.', sector: C },
  { codigo: '33110', descripcion: 'Reparación y mantenimiento de productos metálicos elaborados', sector: C },
  { codigo: '33120', descripcion: 'Reparación y mantenimiento de maquinaria', sector: C },
  { codigo: '33130', descripcion: 'Reparación y mantenimiento de equipo electrónico y óptico', sector: C },
  { codigo: '33140', descripcion: 'Reparación y mantenimiento de equipo eléctrico', sector: C },
  { codigo: '33150', descripcion: 'Reparación y mantenimiento de equipo de transporte', sector: C },
  { codigo: '33190', descripcion: 'Reparación y mantenimiento de otros tipos de equipo', sector: C },
  { codigo: '33200', descripcion: 'Instalación de maquinaria y equipos industriales', sector: C },

  // ── D · Suministro de electricidad, gas, vapor y aire acondicionado ───────
  { codigo: '35101', descripcion: 'Generación de energía eléctrica', sector: D },
  { codigo: '35102', descripcion: 'Transmisión de energía eléctrica', sector: D },
  { codigo: '35103', descripcion: 'Distribución de energía eléctrica', sector: D },
  { codigo: '35200', descripcion: 'Fabricación y distribución de gas por tuberías', sector: D },
  { codigo: '35300', descripcion: 'Suministro de vapor y de agua caliente', sector: D },

  // ── E · Suministro de agua; alcantarillado, gestión de desechos ──────────
  { codigo: '36000', descripcion: 'Captación, tratamiento y distribución de agua', sector: E },
  { codigo: '37000', descripcion: 'Evacuación y tratamiento de aguas residuales', sector: E },
  { codigo: '38110', descripcion: 'Recogida y transporte de desechos no peligrosos', sector: E },
  { codigo: '38120', descripcion: 'Recogida de desechos peligrosos', sector: E },
  { codigo: '38210', descripcion: 'Tratamiento y eliminación de desechos no peligrosos', sector: E },
  { codigo: '38220', descripcion: 'Tratamiento y eliminación de desechos peligrosos', sector: E },
  { codigo: '38301', descripcion: 'Reciclamiento de desechos y desperdicios textiles', sector: E },
  { codigo: '38302', descripcion: 'Reciclamiento de desechos de plástico y caucho', sector: E },
  { codigo: '38303', descripcion: 'Reciclamiento de desechos de vidrio', sector: E },
  { codigo: '38304', descripcion: 'Reciclamiento de desechos de papel y cartón', sector: E },
  { codigo: '38305', descripcion: 'Reciclamiento de desechos metálicos', sector: E },
  { codigo: '38309', descripcion: 'Reciclamiento de desechos no metálicos n.c.p.', sector: E },
  { codigo: '39000', descripcion: 'Actividades de saneamiento y otros servicios de gestión de desechos', sector: E },

  // ── F · Construcción ─────────────────────────────────────────────────────
  { codigo: '41001', descripcion: 'Construcción de edificios residenciales', sector: F },
  { codigo: '41002', descripcion: 'Construcción de edificios no residenciales', sector: F },
  { codigo: '42100', descripcion: 'Construcción de carreteras, calles y caminos', sector: F },
  { codigo: '42200', descripcion: 'Construcción de proyectos de servicio público', sector: F },
  { codigo: '42900', descripcion: 'Construcción de otras obras de ingeniería civil n.c.p.', sector: F },
  { codigo: '43110', descripcion: 'Demolición', sector: F },
  { codigo: '43120', descripcion: 'Preparación del terreno', sector: F },
  { codigo: '43210', descripcion: 'Instalaciones eléctricas', sector: F },
  { codigo: '43220', descripcion: 'Plomería e instalación de calefacción y aire acondicionado', sector: F },
  { codigo: '43290', descripcion: 'Otras instalaciones para obras de construcción', sector: F },
  { codigo: '43300', descripcion: 'Terminación y acabado de edificios', sector: F },
  { codigo: '43900', descripcion: 'Otras actividades especializadas de construcción', sector: F },
  { codigo: '43901', descripcion: 'Fabricación de techos y materiales de construcción', sector: F },

  // ── G · Comercio al por mayor y al por menor ─────────────────────────────
  { codigo: '45100', descripcion: 'Venta de vehículos automotores', sector: G },
  { codigo: '45201', descripcion: 'Reparación mecánica de vehículos automotores', sector: G },
  { codigo: '45202', descripcion: 'Reparación eléctrica de vehículos y recarga de baterías', sector: G },
  { codigo: '45203', descripcion: 'Enderezado y pintura de vehículos automotores', sector: G },
  { codigo: '45204', descripcion: 'Reparación de radiadores, escapes y silenciadores', sector: G },
  { codigo: '45205', descripcion: 'Reparación de artículos de fibra de vidrio', sector: G },
  { codigo: '45206', descripcion: 'Reparación de neumáticos de vehículos', sector: G },
  { codigo: '45207', descripcion: 'Polarizado de vidrios de vehículos', sector: G },
  { codigo: '45208', descripcion: 'Lavado y encerado de vehículos', sector: G },
  { codigo: '45209', descripcion: 'Reparación de vehículos automotores n.c.p.', sector: G },
  { codigo: '45211', descripcion: 'Servicio de grúa para vehículos', sector: G },
  { codigo: '45301', descripcion: 'Venta de partes y accesorios nuevos para vehículos', sector: G },
  { codigo: '45302', descripcion: 'Venta de partes y accesorios usados para vehículos', sector: G },
  { codigo: '45401', descripcion: 'Venta de motocicletas', sector: G },
  { codigo: '45402', descripcion: 'Venta de partes y accesorios para motocicletas', sector: G },
  { codigo: '45403', descripcion: 'Mantenimiento y reparación de motocicletas', sector: G },
  { codigo: '46100', descripcion: 'Venta al por mayor a comisión', sector: G },
  { codigo: '46201', descripcion: 'Venta al por mayor de materias primas agropecuarias', sector: G },
  { codigo: '46202', descripcion: 'Venta al por mayor de productos forestales', sector: G },
  { codigo: '46203', descripcion: 'Venta al por mayor de animales vivos y productos de granja', sector: G },
  { codigo: '46211', descripcion: 'Venta al por mayor de productos agrícolas', sector: G },
  { codigo: '46291', descripcion: 'Venta al por mayor de granos', sector: G },
  { codigo: '46292', descripcion: 'Venta al por mayor de semilla mejorada', sector: G },
  { codigo: '46293', descripcion: 'Venta al por mayor de café y uva', sector: G },
  { codigo: '46294', descripcion: 'Venta al por mayor de caña de azúcar', sector: G },
  { codigo: '46295', descripcion: 'Venta al por mayor de flores y plantas', sector: G },
  { codigo: '46296', descripcion: 'Venta al por mayor de productos agrícolas en general', sector: G },
  { codigo: '46297', descripcion: 'Venta al por mayor de ganado bovino vivo', sector: G },
  { codigo: '46298', descripcion: 'Venta al por mayor de ganado y aves de corral vivos', sector: G },
  { codigo: '46299', descripcion: 'Venta al por mayor de otras especies animales vivas', sector: G },
  { codigo: '46301', descripcion: 'Venta al por mayor de alimentos', sector: G },
  { codigo: '46302', descripcion: 'Venta al por mayor de bebidas', sector: G },
  { codigo: '46303', descripcion: 'Venta al por mayor de tabaco', sector: G },
  { codigo: '46371', descripcion: 'Venta al por mayor de frutas y hortalizas', sector: G },
  { codigo: '46372', descripcion: 'Venta al por mayor de aves y aves de corral', sector: G },
  { codigo: '46373', descripcion: 'Venta al por mayor de carne de res y cerdo', sector: G },
  { codigo: '46374', descripcion: 'Venta al por mayor de huevos', sector: G },
  { codigo: '46375', descripcion: 'Venta al por mayor de productos lácteos', sector: G },
  { codigo: '46376', descripcion: 'Venta al por mayor de productos de panadería', sector: G },
  { codigo: '46377', descripcion: 'Venta al por mayor de pasta, aceites y grasas', sector: G },
  { codigo: '46378', descripcion: 'Venta al por mayor de sal comestible', sector: G },
  { codigo: '46379', descripcion: 'Venta al por mayor de azúcar', sector: G },
  { codigo: '46391', descripcion: 'Venta al por mayor de alimentos empacados', sector: G },
  { codigo: '46392', descripcion: 'Venta al por mayor de bebidas carbonatadas', sector: G },
  { codigo: '46393', descripcion: 'Venta al por mayor de agua purificada', sector: G },
  { codigo: '46394', descripcion: 'Venta al por mayor de refrescos y bebidas en polvo', sector: G },
  { codigo: '46395', descripcion: 'Venta al por mayor de cerveza y licores', sector: G },
  { codigo: '46396', descripcion: 'Venta al por mayor de hielo', sector: G },
  { codigo: '46411', descripcion: 'Venta al por mayor de hilados y textiles', sector: G },
  { codigo: '46412', descripcion: 'Venta al por mayor de artículos textiles', sector: G },
  { codigo: '46413', descripcion: 'Venta al por mayor de textiles para el hogar', sector: G },
  { codigo: '46414', descripcion: 'Venta al por mayor de prendas de vestir y accesorios', sector: G },
  { codigo: '46415', descripcion: 'Venta al por mayor de ropa usada', sector: G },
  { codigo: '46416', descripcion: 'Venta al por mayor de calzado', sector: G },
  { codigo: '46417', descripcion: 'Venta al por mayor de artículos de cuero y talabartería', sector: G },
  { codigo: '46418', descripcion: 'Venta al por mayor de artículos de piel', sector: G },
  { codigo: '46419', descripcion: 'Venta al por mayor de otros artículos textiles n.c.p.', sector: G },
  { codigo: '46471', descripcion: 'Venta al por mayor de instrumentos musicales', sector: G },
  { codigo: '46472', descripcion: 'Venta al por mayor de colchones y almohadas', sector: G },
  { codigo: '46473', descripcion: 'Venta al por mayor de artículos domésticos de aluminio', sector: G },
  { codigo: '46474', descripcion: 'Venta al por mayor de artículos de plástico y domésticos', sector: G },
  { codigo: '46475', descripcion: 'Venta al por mayor de equipo y suministros fotográficos', sector: G },
  { codigo: '46482', descripcion: 'Venta al por mayor de productos veterinarios', sector: G },
  { codigo: '46483', descripcion: 'Venta al por mayor de productos de belleza y personales', sector: G },
  { codigo: '46484', descripcion: 'Venta al por mayor de productos farmacéuticos', sector: G },
  { codigo: '46491', descripcion: 'Venta al por mayor de productos medicinales y cosméticos', sector: G },
  { codigo: '46492', descripcion: 'Venta al por mayor de relojes y joyería', sector: G },
  { codigo: '46493', descripcion: 'Venta al por mayor de electrodomésticos', sector: G },
  { codigo: '46494', descripcion: 'Venta al por mayor de artículos de bazar', sector: G },
  { codigo: '46495', descripcion: 'Venta al por mayor de artículos ópticos', sector: G },
  { codigo: '46496', descripcion: 'Venta al por mayor de revistas, libros y papelería', sector: G },
  { codigo: '46497', descripcion: 'Venta al por mayor de artículos deportivos y juguetes', sector: G },
  { codigo: '46498', descripcion: 'Venta al por mayor de artículos del hogar usados', sector: G },
  { codigo: '46499', descripcion: 'Venta al por mayor de artículos domésticos y personales n.c.p.', sector: G },
  { codigo: '46500', descripcion: 'Venta al por mayor de bicicletas y accesorios', sector: G },
  { codigo: '46510', descripcion: 'Venta al por mayor de computadoras y software', sector: G },
  { codigo: '46520', descripcion: 'Venta al por mayor de equipo de comunicaciones', sector: G },
  { codigo: '46530', descripcion: 'Venta al por mayor de maquinaria y equipo agropecuario', sector: G },
  { codigo: '46590', descripcion: 'Venta al por mayor de equipo profesional y científico', sector: G },
  { codigo: '46591', descripcion: 'Venta al por mayor de maquinaria y materiales para industria maderera', sector: G },
  { codigo: '46592', descripcion: 'Venta al por mayor de maquinaria e insumos para industria gráfica', sector: G },
  { codigo: '46593', descripcion: 'Venta al por mayor de maquinaria para industria de plástico y caucho', sector: G },
  { codigo: '46594', descripcion: 'Venta al por mayor de maquinaria para industria del metal', sector: G },
  { codigo: '46595', descripcion: 'Venta al por mayor de equipo médico y veterinario', sector: G },
  { codigo: '46596', descripcion: 'Venta al por mayor de maquinaria para industria alimenticia', sector: G },
  { codigo: '46597', descripcion: 'Venta al por mayor de maquinaria para industria textil', sector: G },
  { codigo: '46598', descripcion: 'Venta al por mayor de maquinaria para construcción y minería', sector: G },
  { codigo: '46599', descripcion: 'Venta al por mayor de otras maquinarias y equipos', sector: G },
  { codigo: '46610', descripcion: 'Venta al por mayor de combustibles sólidos, líquidos y gaseosos', sector: G },
  { codigo: '46612', descripcion: 'Venta al por mayor de combustible para vehículos y aviación', sector: G },
  { codigo: '46613', descripcion: 'Venta al por mayor de lubricantes y grasas', sector: G },
  { codigo: '46614', descripcion: 'Venta al por mayor de gas propano', sector: G },
  { codigo: '46615', descripcion: 'Venta al por mayor de leña y carbón', sector: G },
  { codigo: '46620', descripcion: 'Venta al por mayor de metales y minerales metálicos', sector: G },
  { codigo: '46631', descripcion: 'Venta al por mayor de puertas, ventanas y fachadas', sector: G },
  { codigo: '46632', descripcion: 'Venta al por mayor de insumos para ferreterías y pinturerías', sector: G },
  { codigo: '46633', descripcion: 'Venta al por mayor de insumos para vidrierías', sector: G },
  { codigo: '46634', descripcion: 'Venta al por mayor de madera en trozas', sector: G },
  { codigo: '46639', descripcion: 'Venta al por mayor de materiales de construcción n.c.p.', sector: G },
  { codigo: '46691', descripcion: 'Venta al por mayor de sal industrial', sector: G },
  { codigo: '46692', descripcion: 'Venta al por mayor de desechos y subproductos textiles', sector: G },
  { codigo: '46693', descripcion: 'Venta al por mayor de desechos y subproductos metálicos', sector: G },
  { codigo: '46694', descripcion: 'Venta al por mayor de subproductos de papel y cartón', sector: G },
  { codigo: '46695', descripcion: 'Venta al por mayor de fertilizantes y agroquímicos', sector: G },
  { codigo: '46696', descripcion: 'Venta al por mayor de subproductos de plástico', sector: G },
  { codigo: '46697', descripcion: 'Venta al por mayor de tintas y materiales de teñido', sector: G },
  { codigo: '46698', descripcion: 'Venta al por mayor de subproductos químicos y de caucho', sector: G },
  { codigo: '46699', descripcion: 'Venta al por mayor de subproductos industriales n.c.p.', sector: G },
  { codigo: '46701', descripcion: 'Venta al por mayor de algodón en bruto', sector: G },
  { codigo: '46900', descripcion: 'Venta al por mayor de otros productos', sector: G },
  { codigo: '46901', descripcion: 'Venta al por mayor de artículos pirotécnicos', sector: G },
  { codigo: '46902', descripcion: 'Venta al por mayor de artículos de consumo misceláneos', sector: G },
  { codigo: '46903', descripcion: 'Venta al por mayor de armas de fuego y municiones', sector: G },
  { codigo: '46904', descripcion: 'Venta al por mayor de carpas y toldos', sector: G },
  { codigo: '46905', descripcion: 'Venta al por mayor de carteles y rótulos publicitarios', sector: G },
  { codigo: '46906', descripcion: 'Venta al por mayor de artículos promocionales', sector: G },
  { codigo: '47111', descripcion: 'Venta al por menor en supermercados', sector: G },
  { codigo: '47112', descripcion: 'Venta al por menor en tiendas de artículos de primera necesidad', sector: G },
  { codigo: '47119', descripcion: 'Venta al por menor en tiendas de variedad', sector: G },
  { codigo: '47190', descripcion: 'Otras ventas al por menor no especializadas', sector: G },
  { codigo: '47199', descripcion: 'Venta al por menor no especializada con predominio de alimentos', sector: G },
  { codigo: '47211', descripcion: 'Venta al por menor de frutas y hortalizas', sector: G },
  { codigo: '47212', descripcion: 'Venta al por menor de carnes y productos de granja', sector: G },
  { codigo: '47213', descripcion: 'Venta al por menor de pescado y mariscos', sector: G },
  { codigo: '47214', descripcion: 'Venta al por menor de productos lácteos', sector: G },
  { codigo: '47215', descripcion: 'Venta al por menor de productos de panadería', sector: G },
  { codigo: '47216', descripcion: 'Venta al por menor de huevos', sector: G },
  { codigo: '47217', descripcion: 'Venta al por menor de carne y productos cárnicos', sector: G },
  { codigo: '47218', descripcion: 'Venta al por menor de granos', sector: G },
  { codigo: '47219', descripcion: 'Venta al por menor de alimentos n.c.p.', sector: G },
  { codigo: '47221', descripcion: 'Venta al por menor de hielo', sector: G },
  { codigo: '47223', descripcion: 'Venta al por menor de bebidas no alcohólicas', sector: G },
  { codigo: '47224', descripcion: 'Venta al por menor de bebidas alcohólicas (para llevar)', sector: G },
  { codigo: '47225', descripcion: 'Venta al por menor de bebidas alcohólicas (para consumo en el local)', sector: G },
  { codigo: '47230', descripcion: 'Venta al por menor de tabaco', sector: G },
  { codigo: '47300', descripcion: 'Venta al por menor de combustibles y lubricantes', sector: G },
  { codigo: '47411', descripcion: 'Venta al por menor de computadoras y equipo', sector: G },
  { codigo: '47412', descripcion: 'Venta al por menor de equipo de telecomunicaciones', sector: G },
  { codigo: '47420', descripcion: 'Venta al por menor de equipo de audio y video', sector: G },
  { codigo: '47510', descripcion: 'Venta al por menor de hilados, textiles y textiles para el hogar', sector: G },
  { codigo: '47521', descripcion: 'Venta al por menor de productos de madera', sector: G },
  { codigo: '47522', descripcion: 'Venta al por menor de ferretería', sector: G },
  { codigo: '47523', descripcion: 'Venta al por menor de pinturas', sector: G },
  { codigo: '47524', descripcion: 'Venta al por menor de vidriería', sector: G },
  { codigo: '47529', descripcion: 'Venta al por menor de materiales de construcción n.c.p.', sector: G },
  { codigo: '47530', descripcion: 'Venta al por menor de alfombras y revestimientos de pisos y paredes', sector: G },
  { codigo: '47591', descripcion: 'Venta al por menor de muebles', sector: G },
  { codigo: '47592', descripcion: 'Venta al por menor de artículos de bazar', sector: G },
  { codigo: '47593', descripcion: 'Venta al por menor de electrodomésticos', sector: G },
  { codigo: '47594', descripcion: 'Venta al por menor de artículos eléctricos e iluminación', sector: G },
  { codigo: '47598', descripcion: 'Venta al por menor de instrumentos musicales', sector: G },
  { codigo: '47610', descripcion: 'Venta al por menor de libros y artículos de papelería', sector: G },
  { codigo: '47620', descripcion: 'Venta al por menor de discos, videos y similares', sector: G },
  { codigo: '47630', descripcion: 'Venta al por menor de artículos deportivos', sector: G },
  { codigo: '47631', descripcion: 'Venta al por menor de bicicletas y accesorios', sector: G },
  { codigo: '47640', descripcion: 'Venta al por menor de juegos y juguetes', sector: G },
  { codigo: '47711', descripcion: 'Venta al por menor de prendas de vestir y accesorios', sector: G },
  { codigo: '47712', descripcion: 'Venta al por menor de calzado', sector: G },
  { codigo: '47713', descripcion: 'Venta al por menor de artículos de piel, cuero y talabartería', sector: G },
  { codigo: '47721', descripcion: 'Venta al por menor de productos farmacéuticos y artículos médicos', sector: G },
  { codigo: '47722', descripcion: 'Venta al por menor de cosméticos y artículos de tocador', sector: G },
  { codigo: '47731', descripcion: 'Venta al por menor de joyería, artículos ópticos y relojes', sector: G },
  { codigo: '47732', descripcion: 'Venta al por menor de plantas, semillas y animales', sector: G },
  { codigo: '47733', descripcion: 'Venta al por menor de combustible doméstico', sector: G },
  { codigo: '47734', descripcion: 'Venta al por menor de artesanías y cerámica', sector: G },
  { codigo: '47735', descripcion: 'Venta al por menor de ataúdes, trofeos y artículos religiosos', sector: G },
  { codigo: '47736', descripcion: 'Venta al por menor de armas de fuego y municiones', sector: G },
  { codigo: '47737', descripcion: 'Venta al por menor de artículos pirotécnicos', sector: G },
  { codigo: '47738', descripcion: 'Venta al por menor de artículos desechables personales y domésticos', sector: G },
  { codigo: '47739', descripcion: 'Venta al por menor de otros productos n.c.p.', sector: G },
  { codigo: '47741', descripcion: 'Venta al por menor de artículos usados', sector: G },
  { codigo: '47742', descripcion: 'Venta al por menor de textiles y ropa usada', sector: G },
  { codigo: '47743', descripcion: 'Venta al por menor de libros y papel usados', sector: G },
  { codigo: '47749', descripcion: 'Venta al por menor de productos usados n.c.p.', sector: G },
  { codigo: '47811', descripcion: 'Venta al por menor de frutas y hortalizas en puestos de mercado', sector: G },
  { codigo: '47814', descripcion: 'Venta al por menor de productos lácteos en puestos de mercado', sector: G },
  { codigo: '47815', descripcion: 'Venta al por menor de productos de panadería en puestos de mercado', sector: G },
  { codigo: '47816', descripcion: 'Venta al por menor de bebidas en puestos de mercado', sector: G },
  { codigo: '47818', descripcion: 'Venta al por menor en puestos de mercado', sector: G },
  { codigo: '47821', descripcion: 'Venta al por menor de hilados y textiles en puestos de mercado', sector: G },
  { codigo: '47822', descripcion: 'Venta al por menor de artículos textiles en puestos de mercado', sector: G },
  { codigo: '47823', descripcion: 'Venta al por menor de textiles para el hogar en puestos de mercado', sector: G },
  { codigo: '47824', descripcion: 'Venta al por menor de ropa y accesorios en puestos de mercado', sector: G },
  { codigo: '47825', descripcion: 'Venta al por menor de ropa usada en puestos de mercado', sector: G },
  { codigo: '47826', descripcion: 'Venta al por menor de calzado en puestos de mercado', sector: G },
  { codigo: '47827', descripcion: 'Venta al por menor de artículos de cuero en puestos de mercado', sector: G },
  { codigo: '47829', descripcion: 'Venta al por menor de artículos textiles en puestos de mercado n.c.p.', sector: G },
  { codigo: '47891', descripcion: 'Venta al por menor de animales y flores en puestos de mercado', sector: G },
  { codigo: '47892', descripcion: 'Venta al por menor de cosméticos y medicamentos en puestos de mercado', sector: G },
  { codigo: '47893', descripcion: 'Venta al por menor de artículos de bazar en puestos de mercado', sector: G },
  { codigo: '47894', descripcion: 'Venta al por menor de libros y periódicos en puestos de mercado', sector: G },
  { codigo: '47895', descripcion: 'Venta al por menor de materiales de construcción en puestos de mercado', sector: G },
  { codigo: '47896', descripcion: 'Venta al por menor de equipo de comunicaciones en puestos de mercado', sector: G },
  { codigo: '47899', descripcion: 'Venta al por menor en puestos de mercado n.c.p.', sector: G },
  { codigo: '47910', descripcion: 'Venta al por menor por correo e internet', sector: G },
  { codigo: '47990', descripcion: 'Otras ventas al por menor no realizadas en tiendas', sector: G },

  // ── H · Transporte y almacenamiento ──────────────────────────────────────
  { codigo: '49110', descripcion: 'Transporte interurbano de pasajeros por ferrocarril', sector: H },
  { codigo: '49120', descripcion: 'Transporte de carga por ferrocarril', sector: H },
  { codigo: '49211', descripcion: 'Transporte urbano e interurbano de pasajeros en autobús', sector: H },
  { codigo: '49212', descripcion: 'Transporte interdepartamental de pasajeros en microbús', sector: H },
  { codigo: '49213', descripcion: 'Transporte urbano e interurbano de pasajeros en microbús', sector: H },
  { codigo: '49214', descripcion: 'Transporte interdepartamental de pasajeros en autobús', sector: H },
  { codigo: '49221', descripcion: 'Transporte internacional de pasajeros', sector: H },
  { codigo: '49222', descripcion: 'Servicio de taxi y vehículo con chofer', sector: H },
  { codigo: '49223', descripcion: 'Transporte escolar', sector: H },
  { codigo: '49225', descripcion: 'Transporte de pasajeros en excursiones', sector: H },
  { codigo: '49226', descripcion: 'Servicio de transporte de personal', sector: H },
  { codigo: '49229', descripcion: 'Transporte terrestre de pasajeros n.c.p.', sector: H },
  { codigo: '49231', descripcion: 'Transporte urbano de carga', sector: H },
  { codigo: '49232', descripcion: 'Transporte nacional de carga', sector: H },
  { codigo: '49233', descripcion: 'Transporte internacional de carga', sector: H },
  { codigo: '49234', descripcion: 'Servicio de mudanzas', sector: H },
  { codigo: '49235', descripcion: 'Alquiler de vehículos de carga con conductor', sector: H },
  { codigo: '49300', descripcion: 'Transporte por tuberías', sector: H },
  { codigo: '50110', descripcion: 'Transporte marítimo de pasajeros', sector: H },
  { codigo: '50120', descripcion: 'Transporte marítimo de carga', sector: H },
  { codigo: '50211', descripcion: 'Transporte de pasajeros por vías de navegación interior', sector: H },
  { codigo: '50212', descripcion: 'Alquiler de equipo de transporte por vías interiores con operador', sector: H },
  { codigo: '50220', descripcion: 'Transporte de carga por vías de navegación interior', sector: H },
  { codigo: '51100', descripcion: 'Transporte aéreo de pasajeros', sector: H },
  { codigo: '51201', descripcion: 'Transporte aéreo de carga', sector: H },
  { codigo: '51202', descripcion: 'Alquiler de equipo de transporte aéreo de carga con operador', sector: H },
  { codigo: '52101', descripcion: 'Alquiler de instalaciones de almacenamiento en zonas francas', sector: H },
  { codigo: '52102', descripcion: 'Alquiler de silos para granos', sector: H },
  { codigo: '52103', descripcion: 'Alquiler de instalaciones refrigeradas para almacenamiento de alimentos', sector: H },
  { codigo: '52109', descripcion: 'Alquiler de depósitos y bodegas n.c.p.', sector: H },
  { codigo: '52211', descripcion: 'Servicios de estacionamiento y parqueo', sector: H },
  { codigo: '52212', descripcion: 'Servicios de terminales de transporte terrestre', sector: H },
  { codigo: '52219', descripcion: 'Servicios de transporte terrestre n.c.p.', sector: H },
  { codigo: '52220', descripcion: 'Servicios de transporte por agua', sector: H },
  { codigo: '52230', descripcion: 'Servicios de transporte aéreo', sector: H },
  { codigo: '52240', descripcion: 'Manipulación de carga', sector: H },
  { codigo: '52290', descripcion: 'Otras actividades de apoyo al transporte', sector: H },
  { codigo: '52291', descripcion: 'Agencias de aduanas', sector: H },
  { codigo: '53100', descripcion: 'Actividades postales nacionales', sector: H },
  { codigo: '53200', descripcion: 'Actividades de mensajería y correo distintas a postales nacionales', sector: H },

  // ── I · Actividades de alojamiento y de servicio de comidas ──────────────
  { codigo: '55101', descripcion: 'Actividades de alojamiento de corta duración', sector: I },
  { codigo: '55102', descripcion: 'Hoteles', sector: I },
  { codigo: '55200', descripcion: 'Actividades de campamentos y parques para caravanas', sector: I },
  { codigo: '55900', descripcion: 'Otras actividades de alojamiento n.c.p.', sector: I },
  { codigo: '56101', descripcion: 'Restaurantes', sector: I },
  { codigo: '56106', descripcion: 'Pupuserías', sector: I },
  { codigo: '56107', descripcion: 'Diversas actividades de restaurantes', sector: I },
  { codigo: '56108', descripcion: 'Comedores', sector: I },
  { codigo: '56109', descripcion: 'Servicio móvil de comidas', sector: I },
  { codigo: '56210', descripcion: 'Catering para eventos', sector: I },
  { codigo: '56291', descripcion: 'Suministro de comidas por contrato', sector: I },
  { codigo: '56292', descripcion: 'Concesión de cafeterías y chalets en lugares de trabajo', sector: I },
  { codigo: '56299', descripcion: 'Servicios de preparación de comidas n.c.p.', sector: I },
  { codigo: '56301', descripcion: 'Actividades de bares y salones de bebidas', sector: I },
  { codigo: '56302', descripcion: 'Venta de bebidas en puestos callejeros y mercados', sector: I },

  // ── J · Información y comunicaciones ──────────────────────────────────────
  { codigo: '58110', descripcion: 'Edición de libros y publicaciones musicales', sector: J },
  { codigo: '58120', descripcion: 'Edición de directorios y listas de correo', sector: J },
  { codigo: '58130', descripcion: 'Edición de periódicos y revistas', sector: J },
  { codigo: '58190', descripcion: 'Otras actividades de edición', sector: J },
  { codigo: '58200', descripcion: 'Edición de programas informáticos', sector: J },
  { codigo: '59110', descripcion: 'Actividades de producción cinematográfica', sector: J },
  { codigo: '59120', descripcion: 'Postproducción de películas, videos y programas de televisión', sector: J },
  { codigo: '59130', descripcion: 'Distribución de películas, videos y programas de televisión', sector: J },
  { codigo: '59140', descripcion: 'Exhibición de películas y videos', sector: J },
  { codigo: '59200', descripcion: 'Edición y grabación de música', sector: J },
  { codigo: '60100', descripcion: 'Transmisiones de radio', sector: J },
  { codigo: '60201', descripcion: 'Transmisiones de televisión abierta', sector: J },
  { codigo: '60202', descripcion: 'Transmisiones de televisión por cable y por suscripción', sector: J },
  { codigo: '60299', descripcion: 'Servicios de televisión incluyendo cable', sector: J },
  { codigo: '60900', descripcion: 'Programación y transmisión de radio y televisión', sector: J },
  { codigo: '61101', descripcion: 'Servicio telefónico', sector: J },
  { codigo: '61102', descripcion: 'Servicio de internet', sector: J },
  { codigo: '61103', descripcion: 'Servicio de telefonía fija', sector: J },
  { codigo: '61109', descripcion: 'Servicio de internet n.c.p.', sector: J },
  { codigo: '61201', descripcion: 'Servicio de telefonía móvil', sector: J },
  { codigo: '61202', descripcion: 'Servicio de internet inalámbrico', sector: J },
  { codigo: '61209', descripcion: 'Servicios de telecomunicaciones inalámbricas n.c.p.', sector: J },
  { codigo: '61301', descripcion: 'Telecomunicaciones por satélite', sector: J },
  { codigo: '61309', descripcion: 'Comunicaciones por satélite n.c.p.', sector: J },
  { codigo: '61900', descripcion: 'Otras actividades de telecomunicaciones n.c.p.', sector: J },
  { codigo: '62010', descripcion: 'Programación informática', sector: J },
  { codigo: '62020', descripcion: 'Consultoría de informática y gestión de instalaciones', sector: J },
  { codigo: '62090', descripcion: 'Otras actividades de tecnología de la información y servicios informáticos', sector: J },
  { codigo: '63110', descripcion: 'Procesamiento de datos y actividades conexas', sector: J },
  { codigo: '63120', descripcion: 'Portales web', sector: J },
  { codigo: '63910', descripcion: 'Servicios de agencias de noticias', sector: J },
  { codigo: '63990', descripcion: 'Otras actividades de servicios de información n.c.p.', sector: J },

  // ── K · Actividades financieras y de seguros ──────────────────────────────
  { codigo: '64110', descripcion: 'Actividades del banco central', sector: K },
  { codigo: '64190', descripcion: 'Bancos', sector: K },
  { codigo: '64192', descripcion: 'Entidades de envío de remesas', sector: K },
  { codigo: '64199', descripcion: 'Otras entidades financieras', sector: K },
  { codigo: '64200', descripcion: 'Actividades de holding', sector: K },
  { codigo: '64300', descripcion: 'Fideicomisos y otras fuentes de financiamiento', sector: K },
  { codigo: '64910', descripcion: 'Arrendamiento financiero', sector: K },
  { codigo: '64920', descripcion: 'Actividades de cooperativas de ahorro y crédito', sector: K },
  { codigo: '64921', descripcion: 'Actividades de emisoras de tarjetas de crédito', sector: K },
  { codigo: '64922', descripcion: 'Otros tipos de crédito', sector: K },
  { codigo: '64928', descripcion: 'Prestamistas y casas de empeño', sector: K },
  { codigo: '64990', descripcion: 'Servicios financieros n.c.p.', sector: K },
  { codigo: '65110', descripcion: 'Planes de seguros de vida', sector: K },
  { codigo: '65120', descripcion: 'Planes de seguros generales', sector: K },
  { codigo: '65199', descripcion: 'Seguros generales de todo tipo', sector: K },
  { codigo: '65200', descripcion: 'Reaseguros', sector: K },
  { codigo: '65300', descripcion: 'Planes de pensiones', sector: K },
  { codigo: '66110', descripcion: 'Administración de mercados financieros', sector: K },
  { codigo: '66120', descripcion: 'Actividades de corretaje de valores y de contratos de productos básicos', sector: K },
  { codigo: '66190', descripcion: 'Actividades auxiliares de intermediación financiera n.c.p.', sector: K },
  { codigo: '66210', descripcion: 'Evaluación de riesgos y daños', sector: K },
  { codigo: '66220', descripcion: 'Actividades de agentes y corredores de seguros', sector: K },
  { codigo: '66290', descripcion: 'Otras actividades auxiliares de seguros y pensiones', sector: K },
  { codigo: '66300', descripcion: 'Actividades de gestión de fondos', sector: K },

  // ── L · Actividades inmobiliarias ─────────────────────────────────────────
  { codigo: '68101', descripcion: 'Servicios de arrendamiento y venta de lotes de cementerio', sector: L },
  { codigo: '68109', descripcion: 'Actividades inmobiliarias con bienes propios o arrendados n.c.p.', sector: L },
  { codigo: '68200', descripcion: 'Actividades inmobiliarias a cambio de una retribución o por contrato', sector: L },

  // ── M · Actividades profesionales, científicas y técnicas ─────────────────
  { codigo: '69100', descripcion: 'Actividades jurídicas', sector: M },
  { codigo: '69200', descripcion: 'Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal', sector: M },
  { codigo: '70100', descripcion: 'Actividades de oficinas centrales para sociedades controladoras', sector: M },
  { codigo: '70200', descripcion: 'Actividades de consultoría de gestión empresarial', sector: M },
  { codigo: '71101', descripcion: 'Servicios de arquitectura, urbanismo y planificación', sector: M },
  { codigo: '71102', descripcion: 'Servicios de ingeniería', sector: M },
  { codigo: '71103', descripcion: 'Servicios de topografía, cartografía y geofísica', sector: M },
  { codigo: '71200', descripcion: 'Ensayos y análisis técnicos', sector: M },
  { codigo: '72100', descripcion: 'Investigación y desarrollo experimental en ciencias naturales e ingeniería', sector: M },
  { codigo: '72199', descripcion: 'Investigación científica', sector: M },
  { codigo: '72200', descripcion: 'Investigación y desarrollo en ciencias sociales y humanidades', sector: M },
  { codigo: '73100', descripcion: 'Publicidad', sector: M },
  { codigo: '73200', descripcion: 'Estudios de mercado y encuestas de opinión', sector: M },
  { codigo: '74100', descripcion: 'Actividades especializadas de diseño', sector: M },
  { codigo: '74200', descripcion: 'Actividades de fotografía', sector: M },
  { codigo: '74900', descripcion: 'Otras actividades profesionales, científicas y técnicas n.c.p.', sector: M },
  { codigo: '75000', descripcion: 'Actividades veterinarias', sector: M },

  // ── N · Actividades de servicios administrativos y de apoyo ───────────────
  { codigo: '77101', descripcion: 'Alquiler de equipo de transporte terrestre', sector: N },
  { codigo: '77102', descripcion: 'Alquiler de equipo de transporte acuático', sector: N },
  { codigo: '77103', descripcion: 'Alquiler de equipo de transporte aéreo', sector: N },
  { codigo: '77210', descripcion: 'Alquiler de equipo de recreo y deporte', sector: N },
  { codigo: '77220', descripcion: 'Alquiler de videos y discos', sector: N },
  { codigo: '77290', descripcion: 'Alquiler de otros efectos personales y enseres domésticos', sector: N },
  { codigo: '77300', descripcion: 'Alquiler y arrendamiento de maquinaria y equipo', sector: N },
  { codigo: '77400', descripcion: 'Arrendamiento de propiedad intelectual y productos similares', sector: N },
  { codigo: '78100', descripcion: 'Actividades de colocación y suministro de personal', sector: N },
  { codigo: '78200', descripcion: 'Actividades de agencias de trabajo temporal', sector: N },
  { codigo: '78300', descripcion: 'Suministro y gestión de recursos humanos', sector: N },
  { codigo: '79110', descripcion: 'Actividades de agencias de viajes y operadores de turismo', sector: N },
  { codigo: '79120', descripcion: 'Actividades de operadores turísticos', sector: N },
  { codigo: '79900', descripcion: 'Otros servicios de reservas y actividades conexas', sector: N },
  { codigo: '80100', descripcion: 'Servicios de seguridad privada', sector: N },
  { codigo: '80201', descripcion: 'Actividades de instalación de sistemas de seguridad', sector: N },
  { codigo: '80202', descripcion: 'Prestación de servicios de sistemas de seguridad', sector: N },
  { codigo: '80300', descripcion: 'Actividades de investigación', sector: N },
  { codigo: '81100', descripcion: 'Gestión y mantenimiento combinados de edificios y locales', sector: N },
  { codigo: '81210', descripcion: 'Limpieza general de edificios', sector: N },
  { codigo: '81290', descripcion: 'Otras actividades de mantenimiento combinado de edificios n.c.p.', sector: N },
  { codigo: '81300', descripcion: 'Actividades de paisajismo y servicios de jardinería', sector: N },
  { codigo: '82110', descripcion: 'Actividades combinadas de servicios administrativos de oficina', sector: N },
  { codigo: '82190', descripcion: 'Fotocopiado y actividades similares (sin impresión)', sector: N },
  { codigo: '82200', descripcion: 'Actividades de centros de llamadas', sector: N },
  { codigo: '82300', descripcion: 'Organización de convenciones y eventos comerciales', sector: N },
  { codigo: '82910', descripcion: 'Actividades de agencias de cobro', sector: N },
  { codigo: '82921', descripcion: 'Servicios de empaque de productos alimenticios', sector: N },
  { codigo: '82922', descripcion: 'Servicios de empaque de productos medicinales', sector: N },
  { codigo: '82929', descripcion: 'Servicios de empaque n.c.p.', sector: N },
  { codigo: '82990', descripcion: 'Actividades de apoyo a las empresas n.c.p.', sector: N },

  // ── O · Administración pública y defensa ──────────────────────────────────
  { codigo: '84110', descripcion: 'Actividades de la administración pública en general', sector: O },
  { codigo: '84111', descripcion: 'Concejos municipales', sector: O },
  { codigo: '84120', descripcion: 'Regulación de las actividades de salud, educación y servicios sociales', sector: O },
  { codigo: '84130', descripcion: 'Regulación y facilitación de la actividad económica', sector: O },
  { codigo: '84210', descripcion: 'Actividades del ministerio de relaciones exteriores', sector: O },
  { codigo: '84220', descripcion: 'Actividades de defensa', sector: O },
  { codigo: '84230', descripcion: 'Actividades de mantenimiento del orden público y de seguridad', sector: O },
  { codigo: '84300', descripcion: 'Actividades de planes de seguridad social obligatoria', sector: O },

  // ── P · Enseñanza ─────────────────────────────────────────────────────────
  { codigo: '85101', descripcion: 'Educación de la primera infancia (parvularia)', sector: P },
  { codigo: '85102', descripcion: 'Educación preescolar', sector: P },
  { codigo: '85103', descripcion: 'Educación primaria', sector: P },
  { codigo: '85104', descripcion: 'Educación preescolar y primaria integrada', sector: P },
  { codigo: '85211', descripcion: 'Educación secundaria (7°-9° grado)', sector: P },
  { codigo: '85212', descripcion: 'Educación secundaria general y bachillerato', sector: P },
  { codigo: '85221', descripcion: 'Educación secundaria técnica y vocacional', sector: P },
  { codigo: '85222', descripcion: 'Educación técnica integrada', sector: P },
  { codigo: '85301', descripcion: 'Educación superior universitaria', sector: P },
  { codigo: '85302', descripcion: 'Educación superior no universitaria', sector: P },
  { codigo: '85303', descripcion: 'Educación superior integrada con secundaria y primaria', sector: P },
  { codigo: '85410', descripcion: 'Educación deportiva y recreativa', sector: P },
  { codigo: '85420', descripcion: 'Educación cultural', sector: P },
  { codigo: '85490', descripcion: 'Otros tipos de enseñanza n.c.p.', sector: P },
  { codigo: '85499', descripcion: 'Educación formal', sector: P },
  { codigo: '85500', descripcion: 'Actividades de apoyo a la enseñanza', sector: P },

  // ── Q · Actividades de atención de la salud humana ───────────────────────
  { codigo: '86100', descripcion: 'Actividades de hospitales', sector: Q },
  { codigo: '86201', descripcion: 'Clínicas médicas', sector: Q },
  { codigo: '86202', descripcion: 'Servicios odontológicos', sector: Q },
  { codigo: '86203', descripcion: 'Servicios médicos', sector: Q },
  { codigo: '86901', descripcion: 'Servicios de diagnóstico, análisis y pruebas', sector: Q },
  { codigo: '86902', descripcion: 'Actividades de atención de la salud humana', sector: Q },
  { codigo: '86909', descripcion: 'Otras actividades relacionadas con la salud n.c.p.', sector: Q },
  { codigo: '87100', descripcion: 'Actividades de atención en instituciones con alojamiento para adultos mayores', sector: Q },
  { codigo: '87200', descripcion: 'Instituciones de tratamiento de salud mental y abuso de sustancias', sector: Q },
  { codigo: '87300', descripcion: 'Instituciones de atención de adultos mayores y personas con discapacidad', sector: Q },
  { codigo: '87900', descripcion: 'Actividades de atención a niños y jóvenes', sector: Q },
  { codigo: '87901', descripcion: 'Otras actividades de atención en instituciones', sector: Q },
  { codigo: '88100', descripcion: 'Actividades de asistencia social sin alojamiento para adultos mayores', sector: Q },
  { codigo: '88900', descripcion: 'Otras actividades de servicios sociales sin alojamiento n.c.p.', sector: Q },

  // ── R · Artes, entretenimiento y recreación ───────────────────────────────
  { codigo: '90000', descripcion: 'Actividades creativas, artísticas y de entretenimiento', sector: R },
  { codigo: '91010', descripcion: 'Actividades de bibliotecas y archivos', sector: R },
  { codigo: '91020', descripcion: 'Actividades de museos y preservación de lugares históricos', sector: R },
  { codigo: '91030', descripcion: 'Actividades de jardines botánicos, zoológicos y reservas naturales', sector: R },
  { codigo: '92000', descripcion: 'Actividades de juegos de azar y apuestas', sector: R },
  { codigo: '93110', descripcion: 'Gestión de instalaciones deportivas', sector: R },
  { codigo: '93120', descripcion: 'Actividades de clubes deportivos', sector: R },
  { codigo: '93190', descripcion: 'Otras actividades deportivas', sector: R },
  { codigo: '93210', descripcion: 'Actividades de parques de atracciones y parques temáticos', sector: R },
  { codigo: '93291', descripcion: 'Discotecas y salones de baile', sector: R },
  { codigo: '93298', descripcion: 'Centros vacacionales', sector: R },
  { codigo: '93299', descripcion: 'Otras actividades de entretenimiento y recreación n.c.p.', sector: R },

  // ── S · Otras actividades de servicios ────────────────────────────────────
  { codigo: '94110', descripcion: 'Actividades de organizaciones empresariales y de empleadores', sector: S },
  { codigo: '94120', descripcion: 'Actividades de organizaciones profesionales', sector: S },
  { codigo: '94200', descripcion: 'Actividades de sindicatos de empleados', sector: S },
  { codigo: '94910', descripcion: 'Actividades de organizaciones religiosas', sector: S },
  { codigo: '94920', descripcion: 'Actividades de organizaciones políticas', sector: S },
  { codigo: '94990', descripcion: 'Actividades de otras asociaciones n.c.p.', sector: S },
  { codigo: '95110', descripcion: 'Reparación de computadoras y equipo periférico', sector: S },
  { codigo: '95120', descripcion: 'Reparación de equipo de comunicaciones', sector: S },
  { codigo: '95210', descripcion: 'Reparación de aparatos electrónicos de uso doméstico', sector: S },
  { codigo: '95220', descripcion: 'Reparación de aparatos domésticos', sector: S },
  { codigo: '95230', descripcion: 'Reparación de calzado y artículos de cuero', sector: S },
  { codigo: '95240', descripcion: 'Reparación de muebles', sector: S },
  { codigo: '95291', descripcion: 'Reparación de instrumentos musicales', sector: S },
  { codigo: '95292', descripcion: 'Servicios de cerrajería y duplicado de llaves', sector: S },
  { codigo: '95293', descripcion: 'Reparación de joyas y relojes', sector: S },
  { codigo: '95294', descripcion: 'Reparación de bicicletas y sillas de ruedas', sector: S },
  { codigo: '95299', descripcion: 'Reparación de otros artículos personales n.c.p.', sector: S },
  { codigo: '96010', descripcion: 'Lavandería y tintorería', sector: S },
  { codigo: '96020', descripcion: 'Peluquería y otros tratamientos de belleza', sector: S },
  { codigo: '96030', descripcion: 'Servicios funerarios', sector: S },
  { codigo: '96091', descripcion: 'Saunas y servicios de estética corporal n.c.p.', sector: S },
  { codigo: '96092', descripcion: 'Otros servicios n.c.p.', sector: S },

  // ── T · Actividades de los hogares como empleadores ───────────────────────
  { codigo: '97000', descripcion: 'Actividades de los hogares como empleadores de personal doméstico', sector: T },
  { codigo: '98100', descripcion: 'Actividades indiferenciadas de producción de bienes de los hogares para uso propio', sector: T },
  { codigo: '98200', descripcion: 'Actividades indiferenciadas de producción de servicios de los hogares para uso propio', sector: T },

  // ── U · Actividades de organizaciones extraterritoriales ──────────────────
  { codigo: '99000', descripcion: 'Actividades de organizaciones y órganos extraterritoriales', sector: U },

  // ── Z · Empleados y otras personas naturales ──────────────────────────────
  { codigo: '10001', descripcion: 'Empleados', sector: Z },
  { codigo: '10002', descripcion: 'Jubilados o pensionados', sector: Z },
  { codigo: '10003', descripcion: 'Estudiantes', sector: Z },
  { codigo: '10004', descripcion: 'Desempleados', sector: Z },
  { codigo: '10005', descripcion: 'Otros', sector: Z },
];

// Lookup rápido: código → actividad
const _byCode = new Map(ACTIVIDADES_ECONOMICAS_SV.map((a) => [a.codigo, a]));
export function getActividadByCodigo(codigo: string): ActividadEconomica | undefined {
  return _byCode.get(codigo);
}
