// Catálogos oficiales del Ministerio de Hacienda de El Salvador para DTE.
// Los `value` corresponden a los códigos enviados a FacturaLlama/DTE; se almacenan en BD.

export type DepartamentoSV = { value: string; label: string };
export type MunicipioSV   = { value: string; label: string; department: string };
export type DistritoSV    = { value: string; label: string; department: string; municipality: string };

export const DEPARTAMENTOS_SV: DepartamentoSV[] = [
  { value: '01', label: 'Ahuachapán' },
  { value: '02', label: 'Santa Ana' },
  { value: '03', label: 'Sonsonate' },
  { value: '04', label: 'Chalatenango' },
  { value: '05', label: 'La Libertad' },
  { value: '06', label: 'San Salvador' },
  { value: '07', label: 'Cuscatlán' },
  { value: '08', label: 'La Paz' },
  { value: '09', label: 'Cabañas' },
  { value: '10', label: 'San Vicente' },
  { value: '11', label: 'Usulután' },
  { value: '12', label: 'San Miguel' },
  { value: '13', label: 'Morazán' },
  { value: '14', label: 'La Unión' },
];

export const MUNICIPIOS_SV: MunicipioSV[] = [
  { value: '13', label: 'Ahuachapán Norte',   department: '01' },
  { value: '14', label: 'Ahuachapán Centro',  department: '01' },
  { value: '15', label: 'Ahuachapán Sur',     department: '01' },
  { value: '14', label: 'Santa Ana Norte',    department: '02' },
  { value: '15', label: 'Santa Ana Centro',   department: '02' },
  { value: '16', label: 'Santa Ana Este',     department: '02' },
  { value: '17', label: 'Santa Ana Oeste',    department: '02' },
  { value: '17', label: 'Sonsonate Norte',    department: '03' },
  { value: '18', label: 'Sonsonate Centro',   department: '03' },
  { value: '19', label: 'Sonsonate Este',     department: '03' },
  { value: '20', label: 'Sonsonate Oeste',    department: '03' },
  { value: '34', label: 'Chalatenango Norte', department: '04' },
  { value: '35', label: 'Chalatenango Centro',department: '04' },
  { value: '36', label: 'Chalatenango Sur',   department: '04' },
  { value: '23', label: 'La Libertad Norte',  department: '05' },
  { value: '24', label: 'La Libertad Centro', department: '05' },
  { value: '25', label: 'La Libertad Oeste',  department: '05' },
  { value: '26', label: 'La Libertad Este',   department: '05' },
  { value: '27', label: 'La Libertad Costa',  department: '05' },
  { value: '28', label: 'La Libertad Sur',    department: '05' },
  { value: '20', label: 'San Salvador Norte', department: '06' },
  { value: '21', label: 'San Salvador Oeste', department: '06' },
  { value: '22', label: 'San Salvador Este',  department: '06' },
  { value: '23', label: 'San Salvador Centro',department: '06' },
  { value: '24', label: 'San Salvador Sur',   department: '06' },
  { value: '17', label: 'Cuscatlán Norte',    department: '07' },
  { value: '18', label: 'Cuscatlán Sur',      department: '07' },
  { value: '23', label: 'La Paz Oeste',       department: '08' },
  { value: '24', label: 'La Paz Centro',      department: '08' },
  { value: '25', label: 'La Paz Este',        department: '08' },
  { value: '10', label: 'Cabañas Oeste',      department: '09' },
  { value: '11', label: 'Cabañas Este',       department: '09' },
  { value: '14', label: 'San Vicente Norte',  department: '10' },
  { value: '15', label: 'San Vicente Sur',    department: '10' },
  { value: '24', label: 'Usulután Norte',     department: '11' },
  { value: '25', label: 'Usulután Este',      department: '11' },
  { value: '26', label: 'Usulután Oeste',     department: '11' },
  { value: '21', label: 'San Miguel Norte',   department: '12' },
  { value: '22', label: 'San Miguel Centro',  department: '12' },
  { value: '23', label: 'San Miguel Oeste',   department: '12' },
  { value: '27', label: 'Morazán Norte',      department: '13' },
  { value: '28', label: 'Morazán Sur',        department: '13' },
  { value: '19', label: 'La Unión Norte',     department: '14' },
  { value: '20', label: 'La Unión Sur',       department: '14' },
];

export function getMunicipiosByDept(deptCode: string): MunicipioSV[] {
  return MUNICIPIOS_SV.filter((m) => m.department === deptCode);
}

export function resolverDepartamento(val: string | undefined | null): string {
  if (!val) return '—';
  return DEPARTAMENTOS_SV.find((d) => d.value === val)?.label ?? val;
}

export function resolverMunicipio(
  municipioVal: string | undefined | null,
  deptVal: string | undefined | null,
): string {
  if (!municipioVal) return '—';
  return (
    MUNICIPIOS_SV.find((m) => m.value === municipioVal && m.department === (deptVal ?? ''))?.label ??
    municipioVal
  );
}

export const DISTRITOS_SV: DistritoSV[] = [
  { value: '03', label: 'Atiquizaya', department: '01', municipality: '13' },
  { value: '05', label: 'El Refugio', department: '01', municipality: '13' },
  { value: '09', label: 'San Lorenzo', department: '01', municipality: '13' },
  { value: '12', label: 'Turín', department: '01', municipality: '13' },
  { value: '01', label: 'Ahuachapán', department: '01', municipality: '14' },
  { value: '02', label: 'Apaneca', department: '01', municipality: '14' },
  { value: '04', label: 'Concepción de Ataco', department: '01', municipality: '14' },
  { value: '11', label: 'Tacuba', department: '01', municipality: '14' },
  { value: '06', label: 'Guaymango', department: '01', municipality: '15' },
  { value: '07', label: 'Jujutla', department: '01', municipality: '15' },
  { value: '08', label: 'San Francisco Menéndez', department: '01', municipality: '15' },
  { value: '10', label: 'San Pedro Puxtla', department: '01', municipality: '15' },
  { value: '06', label: 'Masahuat', department: '02', municipality: '14' },
  { value: '07', label: 'Metapán', department: '02', municipality: '14' },
  { value: '11', label: 'Santa Rosa Guachipilín', department: '02', municipality: '14' },
  { value: '13', label: 'Texistepeque', department: '02', municipality: '14' },
  { value: '10', label: 'Santa Ana', department: '02', municipality: '15' },
  { value: '02', label: 'Coatepeque', department: '02', municipality: '16' },
  { value: '04', label: 'El Congo', department: '02', municipality: '16' },
  { value: '01', label: 'Candelaria de la Frontera', department: '02', municipality: '17' },
  { value: '03', label: 'Chalchuapa', department: '02', municipality: '17' },
  { value: '05', label: 'El Porvenir', department: '02', municipality: '17' },
  { value: '08', label: 'San Antonio Pajonal', department: '02', municipality: '17' },
  { value: '09', label: 'San Sebastián Salitrillo', department: '02', municipality: '17' },
  { value: '12', label: 'Santiago de la Frontera', department: '02', municipality: '17' },
  { value: '07', label: 'Juayúa', department: '03', municipality: '17' },
  { value: '08', label: 'Nahuizalco', department: '03', municipality: '17' },
  { value: '10', label: 'Salcoatitán', department: '03', municipality: '17' },
  { value: '13', label: 'Santa Catarina Masahuat', department: '03', municipality: '17' },
  { value: '09', label: 'Nahuilingo', department: '03', municipality: '18' },
  { value: '11', label: 'San Antonio del Monte', department: '03', municipality: '18' },
  { value: '14', label: 'Santo Domingo de Guzmán', department: '03', municipality: '18' },
  { value: '15', label: 'Sonsonate', department: '03', municipality: '18' },
  { value: '16', label: 'Sonzacate', department: '03', municipality: '18' },
  { value: '02', label: 'Armenia', department: '03', municipality: '19' },
  { value: '03', label: 'Caluco', department: '03', municipality: '19' },
  { value: '04', label: 'Cuisnahuat', department: '03', municipality: '19' },
  { value: '06', label: 'Izalco', department: '03', municipality: '19' },
  { value: '12', label: 'San Julián', department: '03', municipality: '19' },
  { value: '05', label: 'Santa Isabel Ishuatán', department: '03', municipality: '19' },
  { value: '01', label: 'Acajutla', department: '03', municipality: '20' },
  { value: '04', label: 'Citala', department: '04', municipality: '34' },
  { value: '12', label: 'La Palma', department: '04', municipality: '34' },
  { value: '25', label: 'San Ignacio', department: '04', municipality: '34' },
  { value: '01', label: 'Agua Caliente', department: '04', municipality: '35' },
  { value: '08', label: 'Dulce Nombre de Maria', department: '04', municipality: '35' },
  { value: '10', label: 'El Paraiso', department: '04', municipality: '35' },
  { value: '13', label: 'La Reina', department: '04', municipality: '35' },
  { value: '16', label: 'Nueva Concepcion', department: '04', municipality: '35' },
  { value: '22', label: 'San Fernando', department: '04', municipality: '35' },
  { value: '24', label: 'San Francisco Morazan', department: '04', municipality: '35' },
  { value: '31', label: 'San Rafael', department: '04', municipality: '35' },
  { value: '32', label: 'Santa Rita', department: '04', municipality: '35' },
  { value: '33', label: 'Tejutla', department: '04', municipality: '35' },
  { value: '02', label: 'Arcatao', department: '04', municipality: '36' },
  { value: '03', label: 'Azacualpa', department: '04', municipality: '36' },
  { value: '07', label: 'Chalatenango', department: '04', municipality: '36' },
  { value: '05', label: 'Comalapa', department: '04', municipality: '36' },
  { value: '06', label: 'Concepcion Quezaltepeque', department: '04', municipality: '36' },
  { value: '09', label: 'El Carrizal', department: '04', municipality: '36' },
  { value: '11', label: 'La Laguna', department: '04', municipality: '36' },
  { value: '14', label: 'Las Vueltas', department: '04', municipality: '36' },
  { value: '15', label: 'Nombre de Jesus', department: '04', municipality: '36' },
  { value: '17', label: 'Nueva Trinidad', department: '04', municipality: '36' },
  { value: '18', label: 'Ojos de Agua', department: '04', municipality: '36' },
  { value: '19', label: 'Potonico', department: '04', municipality: '36' },
  { value: '20', label: 'San Antonio de la Cruz', department: '04', municipality: '36' },
  { value: '21', label: 'San Antonio Los Ranchos', department: '04', municipality: '36' },
  { value: '23', label: 'San Francisco Lempa', department: '04', municipality: '36' },
  { value: '26', label: 'San Isidro Labrador', department: '04', municipality: '36' },
  { value: '27', label: 'San Jose Cancasque', department: '04', municipality: '36' },
  { value: '28', label: 'Las Flores', department: '04', municipality: '36' },
  { value: '29', label: 'San Luis del Carmen', department: '04', municipality: '36' },
  { value: '30', label: 'San Miguel de Mercedes', department: '04', municipality: '36' },
  { value: '12', label: 'Quezaltepeque', department: '05', municipality: '23' },
  { value: '16', label: 'San Matias', department: '05', municipality: '23' },
  { value: '17', label: 'San Pablo Tacachico', department: '05', municipality: '23' },
  { value: '02', label: 'Ciudad Arce', department: '05', municipality: '24' },
  { value: '15', label: 'San Juan Opico', department: '05', municipality: '24' },
  { value: '03', label: 'Colon', department: '05', municipality: '25' },
  { value: '07', label: 'Jayaque', department: '05', municipality: '25' },
  { value: '13', label: 'Sacacoyo', department: '05', municipality: '25' },
  { value: '19', label: 'Talnique', department: '05', municipality: '25' },
  { value: '21', label: 'Tepecoyo', department: '05', municipality: '25' },
  { value: '01', label: 'Antiguo Cuscatlan', department: '05', municipality: '26' },
  { value: '06', label: 'Huizucar', department: '05', municipality: '26' },
  { value: '10', label: 'Nuevo Cuscatlan', department: '05', municipality: '26' },
  { value: '14', label: 'San Jose Villanueva', department: '05', municipality: '26' },
  { value: '22', label: 'Zaragoza', department: '05', municipality: '26' },
  { value: '05', label: 'Chiltiupan', department: '05', municipality: '27' },
  { value: '08', label: 'Jicalapa', department: '05', municipality: '27' },
  { value: '09', label: 'La Libertad', department: '05', municipality: '27' },
  { value: '18', label: 'Tamanique', department: '05', municipality: '27' },
  { value: '20', label: 'Teotepeque', department: '05', municipality: '27' },
  { value: '04', label: 'Comasagua', department: '05', municipality: '28' },
  { value: '11', label: 'Santa Tecla', department: '05', municipality: '28' },
  { value: '01', label: 'Aguilares', department: '06', municipality: '20' },
  { value: '05', label: 'El Paisnal', department: '06', municipality: '20' },
  { value: '06', label: 'Guazapa', department: '06', municipality: '20' },
  { value: '02', label: 'Apopa', department: '06', municipality: '21' },
  { value: '09', label: 'Nejapa', department: '06', municipality: '21' },
  { value: '07', label: 'Ilopango', department: '06', municipality: '22' },
  { value: '13', label: 'San Martin', department: '06', municipality: '22' },
  { value: '17', label: 'Soyapango', department: '06', municipality: '22' },
  { value: '18', label: 'Tonacatepeque', department: '06', municipality: '22' },
  { value: '03', label: 'Ayutuxtepeque', department: '06', municipality: '23' },
  { value: '08', label: 'Mejicanos', department: '06', municipality: '23' },
  { value: '14', label: 'San Salvador', department: '06', municipality: '23' },
  { value: '04', label: 'Cuscatancingo', department: '06', municipality: '23' },
  { value: '19', label: 'Ciudad Delgado', department: '06', municipality: '23' },
  { value: '10', label: 'Panchimalco', department: '06', municipality: '24' },
  { value: '11', label: 'Rosario de Mora', department: '06', municipality: '24' },
  { value: '12', label: 'San Marcos', department: '06', municipality: '24' },
  { value: '15', label: 'Santiago Texacuangos', department: '06', municipality: '24' },
  { value: '16', label: 'Santo Tomas', department: '06', municipality: '24' },
  { value: '06', label: 'Oratorio de Concepcion', department: '07', municipality: '17' },
  { value: '07', label: 'San Bartolome Perulapia', department: '07', municipality: '17' },
  { value: '09', label: 'San Jose Guayabal', department: '07', municipality: '17' },
  { value: '10', label: 'San Pedro Perulapan', department: '07', municipality: '17' },
  { value: '15', label: 'Suchitoto', department: '07', municipality: '17' },
  { value: '01', label: 'Candelaria', department: '07', municipality: '18' },
  { value: '02', label: 'Cojutepeque', department: '07', municipality: '18' },
  { value: '03', label: 'El Carmen', department: '07', municipality: '18' },
  { value: '04', label: 'El Rosario', department: '07', municipality: '18' },
  { value: '05', label: 'Monte San Juan', department: '07', municipality: '18' },
  { value: '08', label: 'San Cristobal', department: '07', municipality: '18' },
  { value: '11', label: 'San Rafael Cedros', department: '07', municipality: '18' },
  { value: '12', label: 'San Ramon', department: '07', municipality: '18' },
  { value: '13', label: 'Santa Cruz Analquito', department: '07', municipality: '18' },
  { value: '14', label: 'Santa Cruz Michapa', department: '07', municipality: '18' },
  { value: '16', label: 'Tenancingo', department: '07', municipality: '18' },
  { value: '01', label: 'Cuyultitan', department: '08', municipality: '23' },
  { value: '05', label: 'Olocuilta', department: '08', municipality: '23' },
  { value: '09', label: 'San Francisco Chinameca', department: '08', municipality: '23' },
  { value: '11', label: 'San Juan Talpa', department: '08', municipality: '23' },
  { value: '13', label: 'San Luis Talpa', department: '08', municipality: '23' },
  { value: '15', label: 'San Pedro Masahuat', department: '08', municipality: '23' },
  { value: '20', label: 'Tapalhuaca', department: '08', municipality: '23' },
  { value: '04', label: 'El Rosario', department: '08', municipality: '24' },
  { value: '03', label: 'Jerusalen', department: '08', municipality: '24' },
  { value: '05', label: 'Mercedes La Ceiba', department: '08', municipality: '24' },
  { value: '06', label: 'Paraiso de Osorio', department: '08', municipality: '24' },
  { value: '07', label: 'San Antonio Masahuat', department: '08', municipality: '24' },
  { value: '08', label: 'San Emigdio', department: '08', municipality: '24' },
  { value: '12', label: 'San Juan Tepezontes', department: '08', municipality: '24' },
  { value: '22', label: 'San Luis La Herradura', department: '08', municipality: '24' },
  { value: '14', label: 'San Miguel Tepezontes', department: '08', municipality: '24' },
  { value: '16', label: 'San Pedro Nonualco', department: '08', municipality: '24' },
  { value: '18', label: 'Santa Maria Ostuma', department: '08', municipality: '24' },
  { value: '19', label: 'Santiago Nonualco', department: '08', municipality: '24' },
  { value: '10', label: 'San Juan Nonualco', department: '08', municipality: '25' },
  { value: '17', label: 'San Rafael Obrajuelo', department: '08', municipality: '25' },
  { value: '21', label: 'Zacatecoluca', department: '08', municipality: '25' },
  { value: '09', label: 'Dolores', department: '09', municipality: '11' },
  { value: '02', label: 'Guacotecti', department: '09', municipality: '11' },
  { value: '06', label: 'Sensuntepeque', department: '09', municipality: '11' },
  { value: '08', label: 'Victoria', department: '09', municipality: '11' },
  { value: '05', label: 'San Isidro', department: '09', municipality: '11' },
  { value: '01', label: 'Cinquera', department: '09', municipality: '10' },
  { value: '03', label: 'Ilobasco', department: '09', municipality: '10' },
  { value: '04', label: 'Jutiapa', department: '09', municipality: '10' },
  { value: '07', label: 'Tejutepeque', department: '09', municipality: '10' },
  { value: '01', label: 'Apastepeque', department: '10', municipality: '14' },
  { value: '06', label: 'San Esteban Catarina', department: '10', municipality: '14' },
  { value: '07', label: 'San Ildefonso', department: '10', municipality: '14' },
  { value: '09', label: 'San Lorenzo', department: '10', municipality: '14' },
  { value: '04', label: 'Santa Clara', department: '10', municipality: '14' },
  { value: '05', label: 'Santo Domingo', department: '10', municipality: '14' },
  { value: '02', label: 'Guadalupe', department: '10', municipality: '15' },
  { value: '03', label: 'San Cayetano Istepeque', department: '10', municipality: '15' },
  { value: '10', label: 'San Vicente', department: '10', municipality: '15' },
  { value: '11', label: 'Tecoluca', department: '10', municipality: '15' },
  { value: '12', label: 'Tepetitan', department: '10', municipality: '15' },
  { value: '13', label: 'Verapaz', department: '10', municipality: '15' },
  { value: '01', label: 'Alegría', department: '11', municipality: '24' },
  { value: '02', label: 'Berlín', department: '11', municipality: '24' },
  { value: '05', label: 'El Triunfo', department: '11', municipality: '24' },
  { value: '07', label: 'Estanzuelas', department: '11', municipality: '24' },
  { value: '09', label: 'Jucuapa', department: '11', municipality: '24' },
  { value: '11', label: 'Mercedes Umaña', department: '11', municipality: '24' },
  { value: '12', label: 'Nueva Granada', department: '11', municipality: '24' },
  { value: '16', label: 'San Buenaventura', department: '11', municipality: '24' },
  { value: '21', label: 'Santiago de María', department: '11', municipality: '24' },
  { value: '03', label: 'California', department: '11', municipality: '25' },
  { value: '04', label: 'Concepción Batres', department: '11', municipality: '25' },
  { value: '06', label: 'Ereguayquín', department: '11', municipality: '25' },
  { value: '10', label: 'Jucuarán', department: '11', municipality: '25' },
  { value: '13', label: 'Ozatlán', department: '11', municipality: '25' },
  { value: '17', label: 'San Dionisio', department: '11', municipality: '25' },
  { value: '18', label: 'Santa Elena', department: '11', municipality: '25' },
  { value: '20', label: 'Santa María', department: '11', municipality: '25' },
  { value: '22', label: 'Tecapán', department: '11', municipality: '25' },
  { value: '23', label: 'Usulután', department: '11', municipality: '25' },
  { value: '08', label: 'Jiquilisco', department: '11', municipality: '26' },
  { value: '14', label: 'Puerto El Triunfo', department: '11', municipality: '26' },
  { value: '15', label: 'San Agustín', department: '11', municipality: '26' },
  { value: '19', label: 'San Francisco Javier', department: '11', municipality: '26' },
  { value: '01', label: 'Carolina', department: '12', municipality: '21' },
  { value: '04', label: 'Chapeltique', department: '12', municipality: '21' },
  { value: '02', label: 'Ciudad Barrios', department: '12', municipality: '21' },
  { value: '11', label: 'Nuevo Eden de San Juan', department: '12', municipality: '21' },
  { value: '13', label: 'San Antonio del Mosco', department: '12', municipality: '21' },
  { value: '14', label: 'San Gerardo', department: '12', municipality: '21' },
  { value: '16', label: 'San Luis de la Reina', department: '12', municipality: '21' },
  { value: '19', label: 'Sesori', department: '12', municipality: '21' },
  { value: '06', label: 'Chirilagua', department: '12', municipality: '22' },
  { value: '03', label: 'Comacaran', department: '12', municipality: '22' },
  { value: '09', label: 'Moncagua', department: '12', municipality: '22' },
  { value: '12', label: 'Quelepa', department: '12', municipality: '22' },
  { value: '17', label: 'San Miguel', department: '12', municipality: '22' },
  { value: '20', label: 'Uluazapa', department: '12', municipality: '22' },
  { value: '05', label: 'Chinameca', department: '12', municipality: '23' },
  { value: '07', label: 'El Transito', department: '12', municipality: '23' },
  { value: '08', label: 'Lolotique', department: '12', municipality: '23' },
  { value: '10', label: 'Nueva Guadalupe', department: '12', municipality: '23' },
  { value: '15', label: 'San Jorge', department: '12', municipality: '23' },
  { value: '18', label: 'San Rafael Oriente', department: '12', municipality: '23' },
  { value: '01', label: 'Arambala', department: '13', municipality: '27' },
  { value: '02', label: 'Cacaopera', department: '13', municipality: '27' },
  { value: '03', label: 'Corinto', department: '13', municipality: '27' },
  { value: '04', label: 'El Rosario', department: '13', municipality: '27' },
  { value: '10', label: 'Joateca', department: '13', municipality: '27' },
  { value: '11', label: 'Jocoaitique', department: '13', municipality: '27' },
  { value: '14', label: 'Meanguera', department: '13', municipality: '27' },
  { value: '16', label: 'Perquin', department: '13', municipality: '27' },
  { value: '22', label: 'San Fernando', department: '13', municipality: '27' },
  { value: '05', label: 'San Isidro', department: '13', municipality: '27' },
  { value: '24', label: 'Torola', department: '13', municipality: '27' },
  { value: '04', label: 'Chilanga', department: '13', municipality: '28' },
  { value: '05', label: 'Delicias de Concepcion', department: '13', municipality: '28' },
  { value: '06', label: 'El Divisadero', department: '13', municipality: '28' },
  { value: '08', label: 'Gualococti', department: '13', municipality: '28' },
  { value: '09', label: 'Guatajiagua', department: '13', municipality: '28' },
  { value: '12', label: 'Jocoro', department: '13', municipality: '28' },
  { value: '13', label: 'Lolotiquillo', department: '13', municipality: '28' },
  { value: '15', label: 'Osicala', department: '13', municipality: '28' },
  { value: '17', label: 'San Carlos', department: '13', municipality: '28' },
  { value: '19', label: 'San Francisco Gotera', department: '13', municipality: '28' },
  { value: '21', label: 'San Simon', department: '13', municipality: '28' },
  { value: '22', label: 'Sensembra', department: '13', municipality: '28' },
  { value: '23', label: 'Sociedad', department: '13', municipality: '28' },
  { value: '25', label: 'Yamabal', department: '13', municipality: '28' },
  { value: '26', label: 'Yoloaiquin', department: '13', municipality: '28' },
  { value: '01', label: 'Anamoros', department: '14', municipality: '19' },
  { value: '02', label: 'Bolivar', department: '14', municipality: '19' },
  { value: '03', label: 'Concepcion de Oriente', department: '14', municipality: '19' },
  { value: '06', label: 'El Sauce', department: '14', municipality: '19' },
  { value: '09', label: 'Lislique', department: '14', municipality: '19' },
  { value: '11', label: 'Nueva Esparta', department: '14', municipality: '19' },
  { value: '12', label: 'Pasaquina', department: '14', municipality: '19' },
  { value: '13', label: 'Poloros', department: '14', municipality: '19' },
  { value: '15', label: 'San Jose Las Fuentes', department: '14', municipality: '19' },
  { value: '16', label: 'Santa Rosa de Lima', department: '14', municipality: '19' },
  { value: '04', label: 'Conchagua', department: '14', municipality: '20' },
  { value: '03', label: 'El Carmen', department: '14', municipality: '20' },
  { value: '07', label: 'Intipuca', department: '14', municipality: '20' },
  { value: '08', label: 'La Union', department: '14', municipality: '20' },
  { value: '10', label: 'Meanguera del Golfo', department: '14', municipality: '20' },
  { value: '14', label: 'San Alejo', department: '14', municipality: '20' },
  { value: '17', label: 'Yayantique', department: '14', municipality: '20' },
  { value: '18', label: 'Yucuaiquin', department: '14', municipality: '20' },
];

export function getDistritosByMuniDept(deptCode: string, muniCode: string): DistritoSV[] {
  return DISTRITOS_SV.filter((d) => d.department === deptCode && d.municipality === muniCode);
}

export function resolverDistrito(
  distritoVal: string | undefined | null,
  muniVal: string | undefined | null,
  deptVal: string | undefined | null,
): string {
  if (!distritoVal) return '—';
  return (
    DISTRITOS_SV.find(
      (d) => d.value === distritoVal && d.municipality === (muniVal ?? '') && d.department === (deptVal ?? ''),
    )?.label ?? distritoVal
  );
}

// Re-exporta los sectores oficiales CAT-019 para usar en formularios y filtros.
export { SECTORES_CAT019 as SECTORES } from '@/lib/cat019';
